/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject1,
  PatchDetailsRequest,
  PatchEmergencyContactRequest,
  PatchMarketingConsentRequest,
  PatchPasswordRequest,
  PostAttachPaymentMethodRequest,
} from '../models/index';
import {
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    PatchDetailsRequestFromJSON,
    PatchDetailsRequestToJSON,
    PatchEmergencyContactRequestFromJSON,
    PatchEmergencyContactRequestToJSON,
    PatchMarketingConsentRequestFromJSON,
    PatchMarketingConsentRequestToJSON,
    PatchPasswordRequestFromJSON,
    PatchPasswordRequestToJSON,
    PostAttachPaymentMethodRequestFromJSON,
    PostAttachPaymentMethodRequestToJSON,
} from '../models/index';

export interface PatchDetailsOperationRequest {
    patchDetailsRequest?: PatchDetailsRequest;
}

export interface PatchEmergencyContactOperationRequest {
    patchEmergencyContactRequest?: PatchEmergencyContactRequest;
}

export interface PatchMarketingConsentOperationRequest {
    patchMarketingConsentRequest?: PatchMarketingConsentRequest;
}

export interface PatchPasswordOperationRequest {
    patchPasswordRequest?: PatchPasswordRequest;
}

export interface PatchPhotoConsentRequest {
    patchMarketingConsentRequest?: PatchMarketingConsentRequest;
}

export interface PatchSessionRemindersRequest {
    patchMarketingConsentRequest?: PatchMarketingConsentRequest;
}

export interface PostAttachPaymentMethodOperationRequest {
    postAttachPaymentMethodRequest?: PostAttachPaymentMethodRequest;
}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI {

    /**
     * Update the account holders details.
     * Update details
     */
    async patchDetailsRaw(requestParameters: PatchDetailsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject1>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/account/details`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchDetailsRequestToJSON(requestParameters['patchDetailsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObject1FromJSON(jsonValue));
    }

    /**
     * Update the account holders details.
     * Update details
     */
    async patchDetails(requestParameters: PatchDetailsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject1> {
        const response = await this.patchDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the account holders emergency contact.
     * Update emergency contact
     */
    async patchEmergencyContactRaw(requestParameters: PatchEmergencyContactOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject1>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/account/emergency-contact`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchEmergencyContactRequestToJSON(requestParameters['patchEmergencyContactRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObject1FromJSON(jsonValue));
    }

    /**
     * Update the account holders emergency contact.
     * Update emergency contact
     */
    async patchEmergencyContact(requestParameters: PatchEmergencyContactOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject1> {
        const response = await this.patchEmergencyContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the account holders marketing consent.
     * Update marketing consent
     */
    async patchMarketingConsentRaw(requestParameters: PatchMarketingConsentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/account/marketing-consent`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchMarketingConsentRequestToJSON(requestParameters['patchMarketingConsentRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update the account holders marketing consent.
     * Update marketing consent
     */
    async patchMarketingConsent(requestParameters: PatchMarketingConsentOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchMarketingConsentRaw(requestParameters, initOverrides);
    }

    /**
     * Update the account password.
     * Update password
     */
    async patchPasswordRaw(requestParameters: PatchPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject1>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/account/password`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchPasswordRequestToJSON(requestParameters['patchPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObject1FromJSON(jsonValue));
    }

    /**
     * Update the account password.
     * Update password
     */
    async patchPassword(requestParameters: PatchPasswordOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject1> {
        const response = await this.patchPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the account holders photo consent.
     * Update photo consent
     */
    async patchPhotoConsentRaw(requestParameters: PatchPhotoConsentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/account/photo-consent`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchMarketingConsentRequestToJSON(requestParameters['patchMarketingConsentRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update the account holders photo consent.
     * Update photo consent
     */
    async patchPhotoConsent(requestParameters: PatchPhotoConsentRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchPhotoConsentRaw(requestParameters, initOverrides);
    }

    /**
     * Update the account holders session reminders.
     * Update session reminders
     */
    async patchSessionRemindersRaw(requestParameters: PatchSessionRemindersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/account/session-reminders`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchMarketingConsentRequestToJSON(requestParameters['patchMarketingConsentRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update the account holders session reminders.
     * Update session reminders
     */
    async patchSessionReminders(requestParameters: PatchSessionRemindersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchSessionRemindersRaw(requestParameters, initOverrides);
    }

    /**
     * Attach a payment method to the user.
     * Attach Payment Method
     */
    async postAttachPaymentMethodRaw(requestParameters: PostAttachPaymentMethodOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/account/attach-payment-method`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAttachPaymentMethodRequestToJSON(requestParameters['postAttachPaymentMethodRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Attach a payment method to the user.
     * Attach Payment Method
     */
    async postAttachPaymentMethod(requestParameters: PostAttachPaymentMethodOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postAttachPaymentMethodRaw(requestParameters, initOverrides);
    }

}
