/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  InlineObject2,
  PostForgotPasswordRequest,
  PostRegisterRequest,
  PostResetPasswordRequest,
  PostTokenRequest,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
    PostForgotPasswordRequestFromJSON,
    PostForgotPasswordRequestToJSON,
    PostRegisterRequestFromJSON,
    PostRegisterRequestToJSON,
    PostResetPasswordRequestFromJSON,
    PostResetPasswordRequestToJSON,
    PostTokenRequestFromJSON,
    PostTokenRequestToJSON,
} from '../models/index';

export interface PostForgotPasswordOperationRequest {
    postForgotPasswordRequest?: PostForgotPasswordRequest;
}

export interface PostRegisterOperationRequest {
    postRegisterRequest?: PostRegisterRequest;
}

export interface PostResetPasswordOperationRequest {
    postResetPasswordRequest?: PostResetPasswordRequest;
}

export interface PostTokenOperationRequest {
    postTokenRequest?: PostTokenRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Retrieve the authenticated user.
     * Whoami
     */
    async getWhoamiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject1>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/whoami`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObject1FromJSON(jsonValue));
    }

    /**
     * Retrieve the authenticated user.
     * Whoami
     */
    async getWhoami(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject1> {
        const response = await this.getWhoamiRaw(initOverrides);
        return await response.value();
    }

    /**
     * Request a password reset link.
     * Password reset link
     */
    async postForgotPasswordRaw(requestParameters: PostForgotPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject2>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/forgot-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostForgotPasswordRequestToJSON(requestParameters['postForgotPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObject2FromJSON(jsonValue));
    }

    /**
     * Request a password reset link.
     * Password reset link
     */
    async postForgotPassword(requestParameters: PostForgotPasswordOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject2> {
        const response = await this.postForgotPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register and retrieve a token.
     * Register a user
     */
    async postRegisterRaw(requestParameters: PostRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostRegisterRequestToJSON(requestParameters['postRegisterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * Register and retrieve a token.
     * Register a user
     */
    async postRegister(requestParameters: PostRegisterOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.postRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reset the users password.
     * Reset password
     */
    async postResetPasswordRaw(requestParameters: PostResetPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject2>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/reset-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostResetPasswordRequestToJSON(requestParameters['postResetPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObject2FromJSON(jsonValue));
    }

    /**
     * Reset the users password.
     * Reset password
     */
    async postResetPassword(requestParameters: PostResetPasswordOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject2> {
        const response = await this.postResetPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sign in and retrieve a token.
     * Get a token
     */
    async postTokenRaw(requestParameters: PostTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/token`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostTokenRequestToJSON(requestParameters['postTokenRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * Sign in and retrieve a token.
     * Get a token
     */
    async postToken(requestParameters: PostTokenOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.postTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
