/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetBookingCalculation200Response,
  GetBookings200Response,
  PostBooking201Response,
  PostBookingRequest,
  PostPayBookingRequest,
} from '../models/index';
import {
    GetBookingCalculation200ResponseFromJSON,
    GetBookingCalculation200ResponseToJSON,
    GetBookings200ResponseFromJSON,
    GetBookings200ResponseToJSON,
    PostBooking201ResponseFromJSON,
    PostBooking201ResponseToJSON,
    PostBookingRequestFromJSON,
    PostBookingRequestToJSON,
    PostPayBookingRequestFromJSON,
    PostPayBookingRequestToJSON,
} from '../models/index';

export interface GetBookingRequest {
    bookingRef: string;
}

export interface GetBookingCalculationRequest {
    filterClass: number;
    filterSessions: Array<number>;
    filterStudents: Array<number>;
    filterPrice: number;
    filterPlan?: number;
    filterDiscount?: number;
    filterVoucher?: number;
}

export interface GetBookingsRequest {
    filterProvider?: number;
    filterStudent?: number;
    filterEnded?: boolean;
    include?: string;
}

export interface PostBookingOperationRequest {
    postBookingRequest?: PostBookingRequest;
}

export interface PostPayBookingOperationRequest {
    bookingRef: string;
    postPayBookingRequest?: PostPayBookingRequest;
}

/**
 * 
 */
export class BookingsApi extends runtime.BaseAPI {

    /**
     * Retrieve the booking.
     * Get a booking
     */
    async getBookingRaw(requestParameters: GetBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostBooking201Response>> {
        if (requestParameters['bookingRef'] == null) {
            throw new runtime.RequiredError(
                'bookingRef',
                'Required parameter "bookingRef" was null or undefined when calling getBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings/{bookingRef}`;
        urlPath = urlPath.replace(`{${"bookingRef"}}`, encodeURIComponent(String(requestParameters['bookingRef'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostBooking201ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the booking.
     * Get a booking
     */
    async getBooking(requestParameters: GetBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostBooking201Response> {
        const response = await this.getBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the Booking costs.
     * Calculate booking costs
     */
    async getBookingCalculationRaw(requestParameters: GetBookingCalculationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBookingCalculation200Response>> {
        if (requestParameters['filterClass'] == null) {
            throw new runtime.RequiredError(
                'filterClass',
                'Required parameter "filterClass" was null or undefined when calling getBookingCalculation().'
            );
        }

        if (requestParameters['filterSessions'] == null) {
            throw new runtime.RequiredError(
                'filterSessions',
                'Required parameter "filterSessions" was null or undefined when calling getBookingCalculation().'
            );
        }

        if (requestParameters['filterStudents'] == null) {
            throw new runtime.RequiredError(
                'filterStudents',
                'Required parameter "filterStudents" was null or undefined when calling getBookingCalculation().'
            );
        }

        if (requestParameters['filterPrice'] == null) {
            throw new runtime.RequiredError(
                'filterPrice',
                'Required parameter "filterPrice" was null or undefined when calling getBookingCalculation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filterClass'] != null) {
            queryParameters['filter[class]'] = requestParameters['filterClass'];
        }

        if (requestParameters['filterSessions'] != null) {
            queryParameters['filter[sessions][]'] = requestParameters['filterSessions'];
        }

        if (requestParameters['filterStudents'] != null) {
            queryParameters['filter[students][]'] = requestParameters['filterStudents'];
        }

        if (requestParameters['filterPrice'] != null) {
            queryParameters['filter[price]'] = requestParameters['filterPrice'];
        }

        if (requestParameters['filterPlan'] != null) {
            queryParameters['filter[plan]'] = requestParameters['filterPlan'];
        }

        if (requestParameters['filterDiscount'] != null) {
            queryParameters['filter[discount]'] = requestParameters['filterDiscount'];
        }

        if (requestParameters['filterVoucher'] != null) {
            queryParameters['filter[voucher]'] = requestParameters['filterVoucher'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings/calculate`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBookingCalculation200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the Booking costs.
     * Calculate booking costs
     */
    async getBookingCalculation(requestParameters: GetBookingCalculationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBookingCalculation200Response> {
        const response = await this.getBookingCalculationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a list of bookings.
     * List bookings
     */
    async getBookingsRaw(requestParameters: GetBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBookings200Response>> {
        const queryParameters: any = {};

        if (requestParameters['filterProvider'] != null) {
            queryParameters['filter[provider]'] = requestParameters['filterProvider'];
        }

        if (requestParameters['filterStudent'] != null) {
            queryParameters['filter[student]'] = requestParameters['filterStudent'];
        }

        if (requestParameters['filterEnded'] != null) {
            queryParameters['filter[ended]'] = requestParameters['filterEnded'];
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBookings200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of bookings.
     * List bookings
     */
    async getBookings(requestParameters: GetBookingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBookings200Response> {
        const response = await this.getBookingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new booking.
     * Create a booking
     */
    async postBookingRaw(requestParameters: PostBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostBooking201Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostBookingRequestToJSON(requestParameters['postBookingRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostBooking201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new booking.
     * Create a booking
     */
    async postBooking(requestParameters: PostBookingOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostBooking201Response> {
        const response = await this.postBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Pay a booking.
     * Pay booking
     */
    async postPayBookingRaw(requestParameters: PostPayBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['bookingRef'] == null) {
            throw new runtime.RequiredError(
                'bookingRef',
                'Required parameter "bookingRef" was null or undefined when calling postPayBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings/{bookingRef}/pay`;
        urlPath = urlPath.replace(`{${"bookingRef"}}`, encodeURIComponent(String(requestParameters['bookingRef'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostPayBookingRequestToJSON(requestParameters['postPayBookingRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Pay a booking.
     * Pay booking
     */
    async postPayBooking(requestParameters: PostPayBookingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postPayBookingRaw(requestParameters, initOverrides);
    }

}
