/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAvailableCatchUpSessions200Response,
  PostBookCatchUpRequest,
  PostBooking201Response,
} from '../models/index';
import {
    GetAvailableCatchUpSessions200ResponseFromJSON,
    GetAvailableCatchUpSessions200ResponseToJSON,
    PostBookCatchUpRequestFromJSON,
    PostBookCatchUpRequestToJSON,
    PostBooking201ResponseFromJSON,
    PostBooking201ResponseToJSON,
} from '../models/index';

export interface GetAvailableCatchUpSessionsRequest {
    filterBankedSession?: number;
}

export interface PostBookCatchUpOperationRequest {
    postBookCatchUpRequest?: PostBookCatchUpRequest;
}

/**
 * 
 */
export class CatchUpsApi extends runtime.BaseAPI {

    /**
     * Retrieve a list of available catch-up sessions.
     * List catch-up sessions
     */
    async getAvailableCatchUpSessionsRaw(requestParameters: GetAvailableCatchUpSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAvailableCatchUpSessions200Response>> {
        const queryParameters: any = {};

        if (requestParameters['filterBankedSession'] != null) {
            queryParameters['filter[banked_session]'] = requestParameters['filterBankedSession'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/available-catch-up-sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAvailableCatchUpSessions200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of available catch-up sessions.
     * List catch-up sessions
     */
    async getAvailableCatchUpSessions(requestParameters: GetAvailableCatchUpSessionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAvailableCatchUpSessions200Response> {
        const response = await this.getAvailableCatchUpSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Book a catch-up session.
     * Book catch-up
     */
    async postBookCatchUpRaw(requestParameters: PostBookCatchUpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostBooking201Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catch-ups`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostBookCatchUpRequestToJSON(requestParameters['postBookCatchUpRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostBooking201ResponseFromJSON(jsonValue));
    }

    /**
     * Book a catch-up session.
     * Book catch-up
     */
    async postBookCatchUp(requestParameters: PostBookCatchUpOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostBooking201Response> {
        const response = await this.postBookCatchUpRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
