/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetCharges200Response,
} from '../models/index';
import {
    GetCharges200ResponseFromJSON,
    GetCharges200ResponseToJSON,
} from '../models/index';

export interface GetChargesRequest {
    filterProvider?: number;
}

/**
 * 
 */
export class ChargesApi extends runtime.BaseAPI {

    /**
     * Retrieve a list of charges raised against the authenticated user\'s account, such as failed payment processing fees. Charges are debits: they reduce the account balance and do not appear in payments.
     * List charges
     */
    async getChargesRaw(requestParameters: GetChargesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCharges200Response>> {
        const queryParameters: any = {};

        if (requestParameters['filterProvider'] != null) {
            queryParameters['filter[provider]'] = requestParameters['filterProvider'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/charges`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCharges200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of charges raised against the authenticated user\'s account, such as failed payment processing fees. Charges are debits: they reduce the account balance and do not appear in payments.
     * List charges
     */
    async getCharges(requestParameters: GetChargesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCharges200Response> {
        const response = await this.getChargesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
