/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetClass200Response,
  GetClasses200Response,
} from '../models/index';
import {
    GetClass200ResponseFromJSON,
    GetClass200ResponseToJSON,
    GetClasses200ResponseFromJSON,
    GetClasses200ResponseToJSON,
} from '../models/index';

export interface GetClassRequest {
    classId: string;
}

export interface GetClassCostsRequest {
    filterTerm?: number;
}

export interface GetClassesRequest {
    filterProvider?: number;
    filterTerm?: number;
    filterVenue?: number;
    filterStage?: number;
    filterLatitude?: number;
    filterLongitude?: number;
    filterAgeInterval?: string;
    filterAgeMin?: number;
    filterAgeMax?: number;
    filterAbility?: number;
    filterActivity?: number;
    filterDay?: string;
    filterSearch?: string;
    page?: number;
    limit?: number;
}

/**
 * 
 */
export class ClassesApi extends runtime.BaseAPI {

    /**
     * Retrieve the class.
     * Get a class
     */
    async getClassRaw(requestParameters: GetClassRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetClass200Response>> {
        if (requestParameters['classId'] == null) {
            throw new runtime.RequiredError(
                'classId',
                'Required parameter "classId" was null or undefined when calling getClass().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/classes/{classId}`;
        urlPath = urlPath.replace(`{${"classId"}}`, encodeURIComponent(String(requestParameters['classId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetClass200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the class.
     * Get a class
     */
    async getClass(requestParameters: GetClassRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetClass200Response> {
        const response = await this.getClassRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a list of class costs.
     * List class costs
     */
    async getClassCostsRaw(requestParameters: GetClassCostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const queryParameters: any = {};

        if (requestParameters['filterTerm'] != null) {
            queryParameters['filter[term]'] = requestParameters['filterTerm'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/class-costs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieve a list of class costs.
     * List class costs
     */
    async getClassCosts(requestParameters: GetClassCostsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getClassCostsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a list of classes.
     * List classes
     */
    async getClassesRaw(requestParameters: GetClassesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetClasses200Response>> {
        const queryParameters: any = {};

        if (requestParameters['filterProvider'] != null) {
            queryParameters['filter[provider]'] = requestParameters['filterProvider'];
        }

        if (requestParameters['filterTerm'] != null) {
            queryParameters['filter[term]'] = requestParameters['filterTerm'];
        }

        if (requestParameters['filterVenue'] != null) {
            queryParameters['filter[venue]'] = requestParameters['filterVenue'];
        }

        if (requestParameters['filterStage'] != null) {
            queryParameters['filter[stage]'] = requestParameters['filterStage'];
        }

        if (requestParameters['filterLatitude'] != null) {
            queryParameters['filter[latitude]'] = requestParameters['filterLatitude'];
        }

        if (requestParameters['filterLongitude'] != null) {
            queryParameters['filter[longitude]'] = requestParameters['filterLongitude'];
        }

        if (requestParameters['filterAgeInterval'] != null) {
            queryParameters['filter[age][interval]'] = requestParameters['filterAgeInterval'];
        }

        if (requestParameters['filterAgeMin'] != null) {
            queryParameters['filter[age][min]'] = requestParameters['filterAgeMin'];
        }

        if (requestParameters['filterAgeMax'] != null) {
            queryParameters['filter[age][max]'] = requestParameters['filterAgeMax'];
        }

        if (requestParameters['filterAbility'] != null) {
            queryParameters['filter[ability]'] = requestParameters['filterAbility'];
        }

        if (requestParameters['filterActivity'] != null) {
            queryParameters['filter[activity]'] = requestParameters['filterActivity'];
        }

        if (requestParameters['filterDay'] != null) {
            queryParameters['filter[day]'] = requestParameters['filterDay'];
        }

        if (requestParameters['filterSearch'] != null) {
            queryParameters['filter[search]'] = requestParameters['filterSearch'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/classes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetClasses200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of classes.
     * List classes
     */
    async getClasses(requestParameters: GetClassesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetClasses200Response> {
        const response = await this.getClassesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
