/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetDiscover200Response,
  GetDiscoverFilterBoundsParameter,
} from '../models/index';
import {
    GetDiscover200ResponseFromJSON,
    GetDiscover200ResponseToJSON,
    GetDiscoverFilterBoundsParameterFromJSON,
    GetDiscoverFilterBoundsParameterToJSON,
} from '../models/index';

export interface GetDiscoverRequest {
    filterType: GetDiscoverFilterTypeEnum;
    filterLatitude: number;
    filterLongitude: number;
    filterCategory?: GetDiscoverFilterCategoryEnum;
    filterRadius?: number;
    filterBounds?: GetDiscoverFilterBoundsParameter;
    sort?: GetDiscoverSortEnum;
    page?: number;
    limit?: number;
}

/**
 * 
 */
export class DiscoverApi extends runtime.BaseAPI {

    /**
     * Retrieve a list of providers or activities.
     * Discover providers or activities
     */
    async getDiscoverRaw(requestParameters: GetDiscoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDiscover200Response>> {
        if (requestParameters['filterType'] == null) {
            throw new runtime.RequiredError(
                'filterType',
                'Required parameter "filterType" was null or undefined when calling getDiscover().'
            );
        }

        if (requestParameters['filterLatitude'] == null) {
            throw new runtime.RequiredError(
                'filterLatitude',
                'Required parameter "filterLatitude" was null or undefined when calling getDiscover().'
            );
        }

        if (requestParameters['filterLongitude'] == null) {
            throw new runtime.RequiredError(
                'filterLongitude',
                'Required parameter "filterLongitude" was null or undefined when calling getDiscover().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filterType'] != null) {
            queryParameters['filter[type]'] = requestParameters['filterType'];
        }

        if (requestParameters['filterCategory'] != null) {
            queryParameters['filter[category]'] = requestParameters['filterCategory'];
        }

        if (requestParameters['filterLatitude'] != null) {
            queryParameters['filter[latitude]'] = requestParameters['filterLatitude'];
        }

        if (requestParameters['filterLongitude'] != null) {
            queryParameters['filter[longitude]'] = requestParameters['filterLongitude'];
        }

        if (requestParameters['filterRadius'] != null) {
            queryParameters['filter[radius]'] = requestParameters['filterRadius'];
        }

        if (requestParameters['filterBounds'] != null) {
            queryParameters['filter[bounds]'] = requestParameters['filterBounds'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/discover`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDiscover200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of providers or activities.
     * Discover providers or activities
     */
    async getDiscover(requestParameters: GetDiscoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDiscover200Response> {
        const response = await this.getDiscoverRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetDiscoverFilterTypeEnum = {
    Provider: 'provider',
    Activity: 'activity'
} as const;
export type GetDiscoverFilterTypeEnum = typeof GetDiscoverFilterTypeEnum[keyof typeof GetDiscoverFilterTypeEnum];
/**
 * @export
 */
export const GetDiscoverFilterCategoryEnum = {
    Create: 'create',
    Explore: 'explore',
    Learn: 'learn',
    Listen: 'listen',
    Move: 'move',
    Perform: 'perform',
    Play: 'play',
    Relax: 'relax',
    Taste: 'taste',
    Watch: 'watch'
} as const;
export type GetDiscoverFilterCategoryEnum = typeof GetDiscoverFilterCategoryEnum[keyof typeof GetDiscoverFilterCategoryEnum];
/**
 * @export
 */
export const GetDiscoverSortEnum = {
    Distance: 'distance',
    Name: 'name'
} as const;
export type GetDiscoverSortEnum = typeof GetDiscoverSortEnum[keyof typeof GetDiscoverSortEnum];
