/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetMetric200Response,
} from '../models/index';
import {
    GetMetric200ResponseFromJSON,
    GetMetric200ResponseToJSON,
} from '../models/index';

export interface GetMetricRequest {
    domain: string;
    metric: string;
    providerId?: number;
    filterDateRange?: string;
}

/**
 * 
 */
export class MetricsApi extends runtime.BaseAPI {

    /**
     * Retrieve the metric.
     * Get a metric
     */
    async getMetricRaw(requestParameters: GetMetricRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMetric200Response>> {
        if (requestParameters['domain'] == null) {
            throw new runtime.RequiredError(
                'domain',
                'Required parameter "domain" was null or undefined when calling getMetric().'
            );
        }

        if (requestParameters['metric'] == null) {
            throw new runtime.RequiredError(
                'metric',
                'Required parameter "metric" was null or undefined when calling getMetric().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['providerId'] != null) {
            queryParameters['provider_id'] = requestParameters['providerId'];
        }

        if (requestParameters['filterDateRange'] != null) {
            queryParameters['filter[date_range]'] = requestParameters['filterDateRange'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/metics/{domain}/{metric}`;
        urlPath = urlPath.replace(`{${"domain"}}`, encodeURIComponent(String(requestParameters['domain'])));
        urlPath = urlPath.replace(`{${"metric"}}`, encodeURIComponent(String(requestParameters['metric'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMetric200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the metric.
     * Get a metric
     */
    async getMetric(requestParameters: GetMetricRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMetric200Response> {
        const response = await this.getMetricRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
