/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetOrders200Response,
} from '../models/index';
import {
    GetOrders200ResponseFromJSON,
    GetOrders200ResponseToJSON,
} from '../models/index';

export interface GetOrdersRequest {
    filterProvider?: number;
}

/**
 * 
 */
export class OrdersApi extends runtime.BaseAPI {

    /**
     * Retrieve a list of product orders placed by the authenticated user. Orders are debits: they reduce the account balance.
     * List orders
     */
    async getOrdersRaw(requestParameters: GetOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOrders200Response>> {
        const queryParameters: any = {};

        if (requestParameters['filterProvider'] != null) {
            queryParameters['filter[provider]'] = requestParameters['filterProvider'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOrders200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of product orders placed by the authenticated user. Orders are debits: they reduce the account balance.
     * List orders
     */
    async getOrders(requestParameters: GetOrdersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOrders200Response> {
        const response = await this.getOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
