/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetPrices200Response,
} from '../models/index';
import {
    GetPrices200ResponseFromJSON,
    GetPrices200ResponseToJSON,
} from '../models/index';

export interface GetPricesRequest {
    filterClass: number;
    filterStudents: Array<number>;
}

/**
 * 
 */
export class PricesApi extends runtime.BaseAPI {

    /**
     * Retrieve a list of prices.
     * List prices
     */
    async getPricesRaw(requestParameters: GetPricesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPrices200Response>> {
        if (requestParameters['filterClass'] == null) {
            throw new runtime.RequiredError(
                'filterClass',
                'Required parameter "filterClass" was null or undefined when calling getPrices().'
            );
        }

        if (requestParameters['filterStudents'] == null) {
            throw new runtime.RequiredError(
                'filterStudents',
                'Required parameter "filterStudents" was null or undefined when calling getPrices().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filterClass'] != null) {
            queryParameters['filter[class]'] = requestParameters['filterClass'];
        }

        if (requestParameters['filterStudents'] != null) {
            queryParameters['filter[students][]'] = requestParameters['filterStudents'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/prices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPrices200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of prices.
     * List prices
     */
    async getPrices(requestParameters: GetPricesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPrices200Response> {
        const response = await this.getPricesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
