/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetProvider200Response,
  GetProviders200Response,
} from '../models/index';
import {
    GetProvider200ResponseFromJSON,
    GetProvider200ResponseToJSON,
    GetProviders200ResponseFromJSON,
    GetProviders200ResponseToJSON,
} from '../models/index';

export interface GetProviderRequest {
    providerId: string;
}

export interface GetProvidersRequest {
    filterUser?: number;
}

/**
 * 
 */
export class ProvidersApi extends runtime.BaseAPI {

    /**
     * Retrieve the provider.
     * Get an provider
     */
    async getProviderRaw(requestParameters: GetProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetProvider200Response>> {
        if (requestParameters['providerId'] == null) {
            throw new runtime.RequiredError(
                'providerId',
                'Required parameter "providerId" was null or undefined when calling getProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/providers/{providerId}`;
        urlPath = urlPath.replace(`{${"providerId"}}`, encodeURIComponent(String(requestParameters['providerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetProvider200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the provider.
     * Get an provider
     */
    async getProvider(requestParameters: GetProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetProvider200Response> {
        const response = await this.getProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a list of providers.
     * List providers
     */
    async getProvidersRaw(requestParameters: GetProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetProviders200Response>> {
        const queryParameters: any = {};

        if (requestParameters['filterUser'] != null) {
            queryParameters['filter[user]'] = requestParameters['filterUser'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/providers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetProviders200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of providers.
     * List providers
     */
    async getProviders(requestParameters: GetProvidersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetProviders200Response> {
        const response = await this.getProvidersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
