/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostSetupIntent200Response,
  PostSetupIntentRequest,
} from '../models/index';
import {
    PostSetupIntent200ResponseFromJSON,
    PostSetupIntent200ResponseToJSON,
    PostSetupIntentRequestFromJSON,
    PostSetupIntentRequestToJSON,
} from '../models/index';

export interface PostSetupIntentOperationRequest {
    postSetupIntentRequest?: PostSetupIntentRequest;
}

/**
 * 
 */
export class SetupIntentsApi extends runtime.BaseAPI {

    /**
     * Create a new setup intent.
     * Create a setup intent
     */
    async postSetupIntentRaw(requestParameters: PostSetupIntentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostSetupIntent200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/setup-intents`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostSetupIntentRequestToJSON(requestParameters['postSetupIntentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostSetupIntent200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new setup intent.
     * Create a setup intent
     */
    async postSetupIntent(requestParameters: PostSetupIntentOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostSetupIntent200Response> {
        const response = await this.postSetupIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
