/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostActivateRequest,
  PostConnectAcceptRequest,
} from '../models/index';
import {
    PostActivateRequestFromJSON,
    PostActivateRequestToJSON,
    PostConnectAcceptRequestFromJSON,
    PostConnectAcceptRequestToJSON,
} from '../models/index';

export interface PostActivateOperationRequest {
    postActivateRequest?: PostActivateRequest;
}

export interface PostConnectAcceptOperationRequest {
    providerId: string;
    postConnectAcceptRequest?: PostConnectAcceptRequest;
}

export interface PostConnectRejectRequest {
    providerId: string;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Activate a user account.
     * Activate a user
     */
    async postActivateRaw(requestParameters: PostActivateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/activate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostActivateRequestToJSON(requestParameters['postActivateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Activate a user account.
     * Activate a user
     */
    async postActivate(requestParameters: PostActivateOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postActivateRaw(requestParameters, initOverrides);
    }

    /**
     * Acccept a connect request.
     * Connect accept
     */
    async postConnectAcceptRaw(requestParameters: PostConnectAcceptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['providerId'] == null) {
            throw new runtime.RequiredError(
                'providerId',
                'Required parameter "providerId" was null or undefined when calling postConnectAccept().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/providers/{providerId}/accept`;
        urlPath = urlPath.replace(`{${"providerId"}}`, encodeURIComponent(String(requestParameters['providerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostConnectAcceptRequestToJSON(requestParameters['postConnectAcceptRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Acccept a connect request.
     * Connect accept
     */
    async postConnectAccept(requestParameters: PostConnectAcceptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postConnectAcceptRaw(requestParameters, initOverrides);
    }

    /**
     * Reject a connect request.
     * Connect reject
     */
    async postConnectRejectRaw(requestParameters: PostConnectRejectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['providerId'] == null) {
            throw new runtime.RequiredError(
                'providerId',
                'Required parameter "providerId" was null or undefined when calling postConnectReject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/providers/{providerId}/reject`;
        urlPath = urlPath.replace(`{${"providerId"}}`, encodeURIComponent(String(requestParameters['providerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reject a connect request.
     * Connect reject
     */
    async postConnectReject(requestParameters: PostConnectRejectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postConnectRejectRaw(requestParameters, initOverrides);
    }

}
