/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostVoucher200Response,
  PostVoucherCheck200Response,
  PostVoucherCheckRequest,
  PostVoucherRequest,
} from '../models/index';
import {
    PostVoucher200ResponseFromJSON,
    PostVoucher200ResponseToJSON,
    PostVoucherCheck200ResponseFromJSON,
    PostVoucherCheck200ResponseToJSON,
    PostVoucherCheckRequestFromJSON,
    PostVoucherCheckRequestToJSON,
    PostVoucherRequestFromJSON,
    PostVoucherRequestToJSON,
} from '../models/index';

export interface PostVoucherOperationRequest {
    postVoucherRequest?: PostVoucherRequest;
}

export interface PostVoucherCheckOperationRequest {
    postVoucherCheckRequest?: PostVoucherCheckRequest;
}

/**
 * 
 */
export class VouchersApi extends runtime.BaseAPI {

    /**
     * Create a new voucher.
     * Create a voucher
     */
    async postVoucherRaw(requestParameters: PostVoucherOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostVoucher200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vouchers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostVoucherRequestToJSON(requestParameters['postVoucherRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostVoucher200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new voucher.
     * Create a voucher
     */
    async postVoucher(requestParameters: PostVoucherOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostVoucher200Response> {
        const response = await this.postVoucherRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Check a voucher code.
     * Check a voucher
     */
    async postVoucherCheckRaw(requestParameters: PostVoucherCheckOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostVoucherCheck200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vouchers/check`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostVoucherCheckRequestToJSON(requestParameters['postVoucherCheckRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostVoucherCheck200ResponseFromJSON(jsonValue));
    }

    /**
     * Check a voucher code.
     * Check a voucher
     */
    async postVoucherCheck(requestParameters: PostVoucherCheckOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostVoucherCheck200Response> {
        const response = await this.postVoucherCheckRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
