/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Session } from './Session';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
    SessionToJSONTyped,
} from './Session';

/**
 * 
 * @export
 * @interface BookingSession
 */
export interface BookingSession {
    /**
     * 
     * @type {number}
     * @memberof BookingSession
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof BookingSession
     */
    dateTime: Date;
    /**
     * 
     * @type {boolean}
     * @memberof BookingSession
     */
    attended: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BookingSession
     */
    absent: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BookingSession
     */
    banked: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BookingSession
     */
    cancelled: boolean;
    /**
     * 
     * @type {Session}
     * @memberof BookingSession
     */
    session: Session;
    /**
     * 
     * @type {BookingSession}
     * @memberof BookingSession
     */
    catchUpSession?: BookingSession;
}

/**
 * Check if a given object implements the BookingSession interface.
 */
export function instanceOfBookingSession(value: object): value is BookingSession {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('dateTime' in value) || value['dateTime'] === undefined) return false;
    if (!('attended' in value) || value['attended'] === undefined) return false;
    if (!('absent' in value) || value['absent'] === undefined) return false;
    if (!('banked' in value) || value['banked'] === undefined) return false;
    if (!('cancelled' in value) || value['cancelled'] === undefined) return false;
    if (!('session' in value) || value['session'] === undefined) return false;
    return true;
}

export function BookingSessionFromJSON(json: any): BookingSession {
    return BookingSessionFromJSONTyped(json, false);
}

export function BookingSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingSession {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dateTime': (new Date(json['date_time'])),
        'attended': json['attended'],
        'absent': json['absent'],
        'banked': json['banked'],
        'cancelled': json['cancelled'],
        'session': SessionFromJSON(json['session']),
        'catchUpSession': json['catchUpSession'] == null ? undefined : BookingSessionFromJSON(json['catchUpSession']),
    };
}

export function BookingSessionToJSON(json: any): BookingSession {
    return BookingSessionToJSONTyped(json, false);
}

export function BookingSessionToJSONTyped(value?: BookingSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date_time': ((value['dateTime']).toISOString()),
        'attended': value['attended'],
        'absent': value['absent'],
        'banked': value['banked'],
        'cancelled': value['cancelled'],
        'session': SessionToJSON(value['session']),
        'catchUpSession': BookingSessionToJSON(value['catchUpSession']),
    };
}

