/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingSession } from './BookingSession';
import {
    BookingSessionFromJSON,
    BookingSessionFromJSONTyped,
    BookingSessionToJSON,
    BookingSessionToJSONTyped,
} from './BookingSession';
import type { Class } from './Class';
import {
    ClassFromJSON,
    ClassFromJSONTyped,
    ClassToJSON,
    ClassToJSONTyped,
} from './Class';

/**
 * 
 * @export
 * @interface Booking
 */
export interface Booking {
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    ref: string;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    studentId: number;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    studentName: string;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    providerId: number;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    providerName: string;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    classId: number;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    className: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    teacherName: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    venueName: string;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    net: number;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    gross: number;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    balance: number;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    credit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Booking
     */
    catchUp?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    paymentMethod?: BookingPaymentMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    paymentMethodLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    priceType?: string;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    nextSession?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    nextSessionEndsAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    lastSession?: Date;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    processingPaymentsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    successfulPaymentsCount?: number;
    /**
     * 
     * @type {Array<BookingSession>}
     * @memberof Booking
     */
    sessions: Array<BookingSession>;
    /**
     * 
     * @type {Class}
     * @memberof Booking
     */
    _class?: Class;
}


/**
 * @export
 */
export const BookingPaymentMethodEnum = {
    Card: 'card',
    Subscription: 'subscription',
    Bank: 'bank',
    Bacs: 'bacs'
} as const;
export type BookingPaymentMethodEnum = typeof BookingPaymentMethodEnum[keyof typeof BookingPaymentMethodEnum];


/**
 * Check if a given object implements the Booking interface.
 */
export function instanceOfBooking(value: object): value is Booking {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('studentId' in value) || value['studentId'] === undefined) return false;
    if (!('studentName' in value) || value['studentName'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('providerName' in value) || value['providerName'] === undefined) return false;
    if (!('classId' in value) || value['classId'] === undefined) return false;
    if (!('className' in value) || value['className'] === undefined) return false;
    if (!('teacherName' in value) || value['teacherName'] === undefined) return false;
    if (!('venueName' in value) || value['venueName'] === undefined) return false;
    if (!('net' in value) || value['net'] === undefined) return false;
    if (!('gross' in value) || value['gross'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('sessions' in value) || value['sessions'] === undefined) return false;
    return true;
}

export function BookingFromJSON(json: any): Booking {
    return BookingFromJSONTyped(json, false);
}

export function BookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Booking {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ref': json['ref'],
        'studentId': json['student_id'],
        'studentName': json['student_name'],
        'providerId': json['provider_id'],
        'providerName': json['provider_name'],
        'classId': json['class_id'],
        'className': json['class_name'],
        'teacherName': json['teacher_name'],
        'venueName': json['venue_name'],
        'net': json['net'],
        'gross': json['gross'],
        'balance': json['balance'],
        'credit': json['credit'] == null ? undefined : json['credit'],
        'catchUp': json['catch_up'] == null ? undefined : json['catch_up'],
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
        'paymentMethodLabel': json['payment_method_label'] == null ? undefined : json['payment_method_label'],
        'priceType': json['price_type'] == null ? undefined : json['price_type'],
        'nextSession': json['next_session'] == null ? undefined : (new Date(json['next_session'])),
        'nextSessionEndsAt': json['next_session_ends_at'] == null ? undefined : (new Date(json['next_session_ends_at'])),
        'lastSession': json['last_session'] == null ? undefined : (new Date(json['last_session'])),
        'processingPaymentsCount': json['processing_payments_count'] == null ? undefined : json['processing_payments_count'],
        'successfulPaymentsCount': json['successful_payments_count'] == null ? undefined : json['successful_payments_count'],
        'sessions': ((json['sessions'] as Array<any>).map(BookingSessionFromJSON)),
        '_class': json['class'] == null ? undefined : ClassFromJSON(json['class']),
    };
}

export function BookingToJSON(json: any): Booking {
    return BookingToJSONTyped(json, false);
}

export function BookingToJSONTyped(value?: Booking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ref': value['ref'],
        'student_id': value['studentId'],
        'student_name': value['studentName'],
        'provider_id': value['providerId'],
        'provider_name': value['providerName'],
        'class_id': value['classId'],
        'class_name': value['className'],
        'teacher_name': value['teacherName'],
        'venue_name': value['venueName'],
        'net': value['net'],
        'gross': value['gross'],
        'balance': value['balance'],
        'credit': value['credit'],
        'catch_up': value['catchUp'],
        'payment_method': value['paymentMethod'],
        'payment_method_label': value['paymentMethodLabel'],
        'price_type': value['priceType'],
        'next_session': value['nextSession'] == null ? undefined : ((value['nextSession']).toISOString()),
        'next_session_ends_at': value['nextSessionEndsAt'] == null ? undefined : ((value['nextSessionEndsAt']).toISOString()),
        'last_session': value['lastSession'] == null ? undefined : ((value['lastSession']).toISOString()),
        'processing_payments_count': value['processingPaymentsCount'],
        'successful_payments_count': value['successfulPaymentsCount'],
        'sessions': ((value['sessions'] as Array<any>).map(BookingSessionToJSON)),
        'class': ClassToJSON(value['_class']),
    };
}

