/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Student } from './Student';
import {
    StudentFromJSON,
    StudentFromJSONTyped,
    StudentToJSON,
    StudentToJSONTyped,
} from './Student';

/**
 * 
 * @export
 * @interface Charge
 */
export interface Charge {
    /**
     * 
     * @type {number}
     * @memberof Charge
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Charge
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof Charge
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof Charge
     */
    providerName: string;
    /**
     * 
     * @type {Date}
     * @memberof Charge
     */
    createdAt: Date;
    /**
     * 
     * @type {Student}
     * @memberof Charge
     */
    student?: Student;
}

/**
 * Check if a given object implements the Charge interface.
 */
export function instanceOfCharge(value: object): value is Charge {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('providerName' in value) || value['providerName'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ChargeFromJSON(json: any): Charge {
    return ChargeFromJSONTyped(json, false);
}

export function ChargeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Charge {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'],
        'amount': json['amount'],
        'providerName': json['provider_name'],
        'createdAt': (new Date(json['created_at'])),
        'student': json['student'] == null ? undefined : StudentFromJSON(json['student']),
    };
}

export function ChargeToJSON(json: any): Charge {
    return ChargeToJSONTyped(json, false);
}

export function ChargeToJSONTyped(value?: Charge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'amount': value['amount'],
        'provider_name': value['providerName'],
        'created_at': ((value['createdAt']).toISOString()),
        'student': StudentToJSON(value['student']),
    };
}

