/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Venue } from './Venue';
import {
    VenueFromJSON,
    VenueFromJSONTyped,
    VenueToJSON,
    VenueToJSONTyped,
} from './Venue';
import type { Session } from './Session';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
    SessionToJSONTyped,
} from './Session';

/**
 * 
 * @export
 * @interface ClassWithType
 */
export interface ClassWithType {
    /**
     * 
     * @type {number}
     * @memberof ClassWithType
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ClassWithType
     */
    activityId?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassWithType
     */
    sessionCost?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ClassWithType
     */
    trialAllowed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ClassWithType
     */
    trialCost?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    ageRange?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClassWithType
     */
    sell?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    term?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    teacher?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassWithType
     */
    venueId?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    venueName?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassWithType
     */
    providerId?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    providerName?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    providerClassImage?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    providerHandle?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    stage?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    stageClassImage?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    venueImage?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    ability?: ClassWithTypeAbilityEnum;
    /**
     * 
     * @type {number}
     * @memberof ClassWithType
     */
    spacesCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ClassWithType
     */
    invitedWaiteesCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof ClassWithType
     */
    nextSession?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ClassWithType
     */
    nextSessionEndsAt?: Date;
    /**
     * 
     * @type {Array<Session>}
     * @memberof ClassWithType
     */
    sessions?: Array<Session>;
    /**
     * 
     * @type {Venue}
     * @memberof ClassWithType
     */
    venue?: Venue;
    /**
     * 
     * @type {string}
     * @memberof ClassWithType
     */
    type: ClassWithTypeTypeEnum;
}


/**
 * @export
 */
export const ClassWithTypeAbilityEnum = {
    Beginner: 'Beginner',
    Intermediate: 'Intermediate',
    Advanced: 'Advanced'
} as const;
export type ClassWithTypeAbilityEnum = typeof ClassWithTypeAbilityEnum[keyof typeof ClassWithTypeAbilityEnum];

/**
 * @export
 */
export const ClassWithTypeTypeEnum = {
    Activity: 'activity'
} as const;
export type ClassWithTypeTypeEnum = typeof ClassWithTypeTypeEnum[keyof typeof ClassWithTypeTypeEnum];


/**
 * Check if a given object implements the ClassWithType interface.
 */
export function instanceOfClassWithType(value: object): value is ClassWithType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ClassWithTypeFromJSON(json: any): ClassWithType {
    return ClassWithTypeFromJSONTyped(json, false);
}

export function ClassWithTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassWithType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'activityId': json['activity_id'] == null ? undefined : json['activity_id'],
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'description': json['description'] == null ? undefined : json['description'],
        'sessionCost': json['session_cost'] == null ? undefined : json['session_cost'],
        'trialAllowed': json['trial_allowed'] == null ? undefined : json['trial_allowed'],
        'trialCost': json['trial_cost'] == null ? undefined : json['trial_cost'],
        'ageRange': json['age_range'] == null ? undefined : json['age_range'],
        'sell': json['sell'] == null ? undefined : json['sell'],
        'term': json['term'] == null ? undefined : json['term'],
        'teacher': json['teacher'] == null ? undefined : json['teacher'],
        'venueId': json['venue_id'] == null ? undefined : json['venue_id'],
        'venueName': json['venue_name'] == null ? undefined : json['venue_name'],
        'providerId': json['provider_id'] == null ? undefined : json['provider_id'],
        'providerName': json['provider_name'] == null ? undefined : json['provider_name'],
        'providerClassImage': json['provider_class_image'] == null ? undefined : json['provider_class_image'],
        'providerHandle': json['provider_handle'] == null ? undefined : json['provider_handle'],
        'stage': json['stage'] == null ? undefined : json['stage'],
        'stageClassImage': json['stage_class_image'] == null ? undefined : json['stage_class_image'],
        'venueImage': json['venue_image'] == null ? undefined : json['venue_image'],
        'ability': json['ability'] == null ? undefined : json['ability'],
        'spacesCount': json['spaces_count'] == null ? undefined : json['spaces_count'],
        'invitedWaiteesCount': json['invited_waitees_count'] == null ? undefined : json['invited_waitees_count'],
        'nextSession': json['next_session'] == null ? undefined : (new Date(json['next_session'])),
        'nextSessionEndsAt': json['next_session_ends_at'] == null ? undefined : (new Date(json['next_session_ends_at'])),
        'sessions': json['sessions'] == null ? undefined : ((json['sessions'] as Array<any>).map(SessionFromJSON)),
        'venue': json['venue'] == null ? undefined : VenueFromJSON(json['venue']),
        'type': json['type'],
    };
}

export function ClassWithTypeToJSON(json: any): ClassWithType {
    return ClassWithTypeToJSONTyped(json, false);
}

export function ClassWithTypeToJSONTyped(value?: ClassWithType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'activity_id': value['activityId'],
        'name': value['name'],
        'image': value['image'],
        'description': value['description'],
        'session_cost': value['sessionCost'],
        'trial_allowed': value['trialAllowed'],
        'trial_cost': value['trialCost'],
        'age_range': value['ageRange'],
        'sell': value['sell'],
        'term': value['term'],
        'teacher': value['teacher'],
        'venue_id': value['venueId'],
        'venue_name': value['venueName'],
        'provider_id': value['providerId'],
        'provider_name': value['providerName'],
        'provider_class_image': value['providerClassImage'],
        'provider_handle': value['providerHandle'],
        'stage': value['stage'],
        'stage_class_image': value['stageClassImage'],
        'venue_image': value['venueImage'],
        'ability': value['ability'],
        'spaces_count': value['spacesCount'],
        'invited_waitees_count': value['invitedWaiteesCount'],
        'next_session': value['nextSession'] == null ? undefined : ((value['nextSession']).toISOString()),
        'next_session_ends_at': value['nextSessionEndsAt'] == null ? undefined : ((value['nextSessionEndsAt']).toISOString()),
        'sessions': value['sessions'] == null ? undefined : ((value['sessions'] as Array<any>).map(SessionToJSON)),
        'venue': VenueToJSON(value['venue']),
        'type': value['type'],
    };
}

