/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Venue } from './Venue';
import {
    VenueFromJSON,
    VenueFromJSONTyped,
    VenueToJSON,
    VenueToJSONTyped,
} from './Venue';
import type { Session } from './Session';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
    SessionToJSONTyped,
} from './Session';

/**
 * 
 * @export
 * @interface Class
 */
export interface Class {
    /**
     * 
     * @type {number}
     * @memberof Class
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Class
     */
    sessionCost: number;
    /**
     * 
     * @type {boolean}
     * @memberof Class
     */
    trialAllowed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Class
     */
    trialCost?: number;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    ageRange?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Class
     */
    sell: boolean;
    /**
     * 
     * @type {number}
     * @memberof Class
     */
    providerId: number;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    providerName: string;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    providerClassImage?: string;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    providerHandle: string;
    /**
     * 
     * @type {boolean}
     * @memberof Class
     */
    providerAgeRange?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    termName: string;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    teacherName: string;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    stageName?: string;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    stageClassImage?: string;
    /**
     * 
     * @type {number}
     * @memberof Class
     */
    spacesCount: number;
    /**
     * 
     * @type {number}
     * @memberof Class
     */
    invitedWaiteesCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Class
     */
    nextSession?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Class
     */
    nextSessionEndsAt?: Date;
    /**
     * 
     * @type {Array<Session>}
     * @memberof Class
     */
    sessions?: Array<Session>;
    /**
     * 
     * @type {Venue}
     * @memberof Class
     */
    venue: Venue;
}

/**
 * Check if a given object implements the Class interface.
 */
export function instanceOfClass(value: object): value is Class {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sessionCost' in value) || value['sessionCost'] === undefined) return false;
    if (!('sell' in value) || value['sell'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('providerName' in value) || value['providerName'] === undefined) return false;
    if (!('providerHandle' in value) || value['providerHandle'] === undefined) return false;
    if (!('termName' in value) || value['termName'] === undefined) return false;
    if (!('teacherName' in value) || value['teacherName'] === undefined) return false;
    if (!('spacesCount' in value) || value['spacesCount'] === undefined) return false;
    if (!('venue' in value) || value['venue'] === undefined) return false;
    return true;
}

export function ClassFromJSON(json: any): Class {
    return ClassFromJSONTyped(json, false);
}

export function ClassFromJSONTyped(json: any, ignoreDiscriminator: boolean): Class {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'description': json['description'] == null ? undefined : json['description'],
        'sessionCost': json['session_cost'],
        'trialAllowed': json['trial_allowed'] == null ? undefined : json['trial_allowed'],
        'trialCost': json['trial_cost'] == null ? undefined : json['trial_cost'],
        'ageRange': json['age_range'] == null ? undefined : json['age_range'],
        'sell': json['sell'],
        'providerId': json['provider_id'],
        'providerName': json['provider_name'],
        'providerClassImage': json['provider_class_image'] == null ? undefined : json['provider_class_image'],
        'providerHandle': json['provider_handle'],
        'providerAgeRange': json['provider_age_range'] == null ? undefined : json['provider_age_range'],
        'termName': json['term_name'],
        'teacherName': json['teacher_name'],
        'stageName': json['stage_name'] == null ? undefined : json['stage_name'],
        'stageClassImage': json['stage_class_image'] == null ? undefined : json['stage_class_image'],
        'spacesCount': json['spaces_count'],
        'invitedWaiteesCount': json['invited_waitees_count'] == null ? undefined : json['invited_waitees_count'],
        'nextSession': json['next_session'] == null ? undefined : (new Date(json['next_session'])),
        'nextSessionEndsAt': json['next_session_ends_at'] == null ? undefined : (new Date(json['next_session_ends_at'])),
        'sessions': json['sessions'] == null ? undefined : ((json['sessions'] as Array<any>).map(SessionFromJSON)),
        'venue': VenueFromJSON(json['venue']),
    };
}

export function ClassToJSON(json: any): Class {
    return ClassToJSONTyped(json, false);
}

export function ClassToJSONTyped(value?: Class | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'description': value['description'],
        'session_cost': value['sessionCost'],
        'trial_allowed': value['trialAllowed'],
        'trial_cost': value['trialCost'],
        'age_range': value['ageRange'],
        'sell': value['sell'],
        'provider_id': value['providerId'],
        'provider_name': value['providerName'],
        'provider_class_image': value['providerClassImage'],
        'provider_handle': value['providerHandle'],
        'provider_age_range': value['providerAgeRange'],
        'term_name': value['termName'],
        'teacher_name': value['teacherName'],
        'stage_name': value['stageName'],
        'stage_class_image': value['stageClassImage'],
        'spaces_count': value['spacesCount'],
        'invited_waitees_count': value['invitedWaiteesCount'],
        'next_session': value['nextSession'] == null ? undefined : ((value['nextSession']).toISOString()),
        'next_session_ends_at': value['nextSessionEndsAt'] == null ? undefined : ((value['nextSessionEndsAt']).toISOString()),
        'sessions': value['sessions'] == null ? undefined : ((value['sessions'] as Array<any>).map(SessionToJSON)),
        'venue': VenueToJSON(value['venue']),
    };
}

