/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Discount
 */
export interface Discount {
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    percentOff?: number;
}

/**
 * Check if a given object implements the Discount interface.
 */
export function instanceOfDiscount(value: object): value is Discount {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DiscountFromJSON(json: any): Discount {
    return DiscountFromJSONTyped(json, false);
}

export function DiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Discount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'percentOff': json['percent_off'] == null ? undefined : json['percent_off'],
    };
}

export function DiscountToJSON(json: any): Discount {
    return DiscountToJSONTyped(json, false);
}

export function DiscountToJSONTyped(value?: Discount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'percent_off': value['percentOff'],
    };
}

