/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Facility = {
    FreeWifi: 'free-wifi',
    LockersAvailable: 'lockers-available',
    OnsiteCaf: 'onsite-café',
    OnsiteParking: 'onsite-parking',
    PetFriendly: 'pet-friendly',
    BabyChanging: 'baby-changing',
    QuietZones: 'quiet-zones',
    SoftPlay: 'soft-play',
    AccessibleParking: 'accessible-parking',
    AccessibleRestrooms: 'accessible-restrooms',
    ChangingPlaces: 'changing-places',
    ServiceDogFriendly: 'service-dog-friendly',
    LiftAccess: 'lift-access',
    StepFreeAccess: 'step-free-access',
    WheelchairAccess: 'wheelchair-access',
    AssistiveTechnologyAvailable: 'assistive-technology-available',
    HearingLoopSystem: 'hearing-loop-system',
    MultilingualInterpretation: 'multilingual-interpretation',
    SignLanguageInterpretation: 'sign-language-interpretation',
    AutismNeurodiversityInclusive: 'autism-neurodiversity-inclusive',
    SendTrained: 'send-trained',
    SmallGroupOptions: 'small-group-options',
    SupportWorkerCarerWelcome: 'support-worker-carer-welcome'
} as const;
export type Facility = typeof Facility[keyof typeof Facility];


export function instanceOfFacility(value: any): boolean {
    for (const key in Facility) {
        if (Object.prototype.hasOwnProperty.call(Facility, key)) {
            if (Facility[key as keyof typeof Facility] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FacilityFromJSON(json: any): Facility {
    return FacilityFromJSONTyped(json, false);
}

export function FacilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Facility {
    return json as Facility;
}

export function FacilityToJSON(value?: Facility | null): any {
    return value as any;
}

export function FacilityToJSONTyped(value: any, ignoreDiscriminator: boolean): Facility {
    return value as Facility;
}

