/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Session } from './Session';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
    SessionToJSONTyped,
} from './Session';

/**
 * 
 * @export
 * @interface GetAvailableCatchUpSessions200Response
 */
export interface GetAvailableCatchUpSessions200Response {
    /**
     * 
     * @type {Array<Session>}
     * @memberof GetAvailableCatchUpSessions200Response
     */
    data?: Array<Session>;
}

/**
 * Check if a given object implements the GetAvailableCatchUpSessions200Response interface.
 */
export function instanceOfGetAvailableCatchUpSessions200Response(value: object): value is GetAvailableCatchUpSessions200Response {
    return true;
}

export function GetAvailableCatchUpSessions200ResponseFromJSON(json: any): GetAvailableCatchUpSessions200Response {
    return GetAvailableCatchUpSessions200ResponseFromJSONTyped(json, false);
}

export function GetAvailableCatchUpSessions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAvailableCatchUpSessions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SessionFromJSON)),
    };
}

export function GetAvailableCatchUpSessions200ResponseToJSON(json: any): GetAvailableCatchUpSessions200Response {
    return GetAvailableCatchUpSessions200ResponseToJSONTyped(json, false);
}

export function GetAvailableCatchUpSessions200ResponseToJSONTyped(value?: GetAvailableCatchUpSessions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SessionToJSON)),
    };
}

