/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAbilities200Response
 */
export interface GetAbilities200Response {
    /**
     * 
     * @type {string}
     * @memberof GetAbilities200Response
     */
    _1?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAbilities200Response
     */
    _2?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAbilities200Response
     */
    _3?: string;
}

/**
 * Check if a given object implements the GetAbilities200Response interface.
 */
export function instanceOfGetAbilities200Response(value: object): value is GetAbilities200Response {
    return true;
}

export function GetAbilities200ResponseFromJSON(json: any): GetAbilities200Response {
    return GetAbilities200ResponseFromJSONTyped(json, false);
}

export function GetAbilities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAbilities200Response {
    if (json == null) {
        return json;
    }
    return {
        
        '_1': json['1'] == null ? undefined : json['1'],
        '_2': json['2'] == null ? undefined : json['2'],
        '_3': json['3'] == null ? undefined : json['3'],
    };
}

export function GetAbilities200ResponseToJSON(json: any): GetAbilities200Response {
    return GetAbilities200ResponseToJSONTyped(json, false);
}

export function GetAbilities200ResponseToJSONTyped(value?: GetAbilities200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '1': value['_1'],
        '2': value['_2'],
        '3': value['_3'],
    };
}

