/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBookingCalculation200Response
 */
export interface GetBookingCalculation200Response {
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    bookingNet?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    bookingDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    bookingFee?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    bookingGross?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    subscriptionNet?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    subscriptionDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    subscriptionFee?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    subscriptionGross?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    subscriptionUpfrontNet?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    subscriptionUpfrontDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    subscriptionUpfrontFee?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    subscriptionUpfrontGross?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    voucherAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    creditAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    amountDue?: number;
    /**
     * 
     * @type {number}
     * @memberof GetBookingCalculation200Response
     */
    paymentIntentAmount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetBookingCalculation200Response
     */
    forceAbsorb?: boolean;
}

/**
 * Check if a given object implements the GetBookingCalculation200Response interface.
 */
export function instanceOfGetBookingCalculation200Response(value: object): value is GetBookingCalculation200Response {
    return true;
}

export function GetBookingCalculation200ResponseFromJSON(json: any): GetBookingCalculation200Response {
    return GetBookingCalculation200ResponseFromJSONTyped(json, false);
}

export function GetBookingCalculation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBookingCalculation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'bookingNet': json['booking_net'] == null ? undefined : json['booking_net'],
        'bookingDiscount': json['booking_discount'] == null ? undefined : json['booking_discount'],
        'bookingFee': json['booking_fee'] == null ? undefined : json['booking_fee'],
        'bookingGross': json['booking_gross'] == null ? undefined : json['booking_gross'],
        'subscriptionNet': json['subscription_net'] == null ? undefined : json['subscription_net'],
        'subscriptionDiscount': json['subscription_discount'] == null ? undefined : json['subscription_discount'],
        'subscriptionFee': json['subscription_fee'] == null ? undefined : json['subscription_fee'],
        'subscriptionGross': json['subscription_gross'] == null ? undefined : json['subscription_gross'],
        'subscriptionUpfrontNet': json['subscription_upfront_net'] == null ? undefined : json['subscription_upfront_net'],
        'subscriptionUpfrontDiscount': json['subscription_upfront_discount'] == null ? undefined : json['subscription_upfront_discount'],
        'subscriptionUpfrontFee': json['subscription_upfront_fee'] == null ? undefined : json['subscription_upfront_fee'],
        'subscriptionUpfrontGross': json['subscription_upfront_gross'] == null ? undefined : json['subscription_upfront_gross'],
        'voucherAmount': json['voucher_amount'] == null ? undefined : json['voucher_amount'],
        'creditAmount': json['credit_amount'] == null ? undefined : json['credit_amount'],
        'amountDue': json['amount_due'] == null ? undefined : json['amount_due'],
        'paymentIntentAmount': json['payment_intent_amount'] == null ? undefined : json['payment_intent_amount'],
        'forceAbsorb': json['force_absorb'] == null ? undefined : json['force_absorb'],
    };
}

export function GetBookingCalculation200ResponseToJSON(json: any): GetBookingCalculation200Response {
    return GetBookingCalculation200ResponseToJSONTyped(json, false);
}

export function GetBookingCalculation200ResponseToJSONTyped(value?: GetBookingCalculation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'booking_net': value['bookingNet'],
        'booking_discount': value['bookingDiscount'],
        'booking_fee': value['bookingFee'],
        'booking_gross': value['bookingGross'],
        'subscription_net': value['subscriptionNet'],
        'subscription_discount': value['subscriptionDiscount'],
        'subscription_fee': value['subscriptionFee'],
        'subscription_gross': value['subscriptionGross'],
        'subscription_upfront_net': value['subscriptionUpfrontNet'],
        'subscription_upfront_discount': value['subscriptionUpfrontDiscount'],
        'subscription_upfront_fee': value['subscriptionUpfrontFee'],
        'subscription_upfront_gross': value['subscriptionUpfrontGross'],
        'voucher_amount': value['voucherAmount'],
        'credit_amount': value['creditAmount'],
        'amount_due': value['amountDue'],
        'payment_intent_amount': value['paymentIntentAmount'],
        'force_absorb': value['forceAbsorb'],
    };
}

