/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Class } from './Class';
import {
    ClassFromJSON,
    ClassFromJSONTyped,
    ClassToJSON,
    ClassToJSONTyped,
} from './Class';

/**
 * 
 * @export
 * @interface GetClass200Response
 */
export interface GetClass200Response {
    /**
     * 
     * @type {Class}
     * @memberof GetClass200Response
     */
    data?: Class;
}

/**
 * Check if a given object implements the GetClass200Response interface.
 */
export function instanceOfGetClass200Response(value: object): value is GetClass200Response {
    return true;
}

export function GetClass200ResponseFromJSON(json: any): GetClass200Response {
    return GetClass200ResponseFromJSONTyped(json, false);
}

export function GetClass200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClass200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ClassFromJSON(json['data']),
    };
}

export function GetClass200ResponseToJSON(json: any): GetClass200Response {
    return GetClass200ResponseToJSONTyped(json, false);
}

export function GetClass200ResponseToJSONTyped(value?: GetClass200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ClassToJSON(value['data']),
    };
}

