/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksFromJSONTyped,
    PaginationLinksToJSON,
    PaginationLinksToJSONTyped,
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { Class } from './Class';
import {
    ClassFromJSON,
    ClassFromJSONTyped,
    ClassToJSON,
    ClassToJSONTyped,
} from './Class';

/**
 * 
 * @export
 * @interface GetClasses200Response
 */
export interface GetClasses200Response {
    /**
     * 
     * @type {Array<Class>}
     * @memberof GetClasses200Response
     */
    data?: Array<Class>;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof GetClasses200Response
     */
    links?: PaginationLinks;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof GetClasses200Response
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the GetClasses200Response interface.
 */
export function instanceOfGetClasses200Response(value: object): value is GetClasses200Response {
    return true;
}

export function GetClasses200ResponseFromJSON(json: any): GetClasses200Response {
    return GetClasses200ResponseFromJSONTyped(json, false);
}

export function GetClasses200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClasses200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ClassFromJSON)),
        'links': json['links'] == null ? undefined : PaginationLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function GetClasses200ResponseToJSON(json: any): GetClasses200Response {
    return GetClasses200ResponseToJSONTyped(json, false);
}

export function GetClasses200ResponseToJSONTyped(value?: GetClasses200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ClassToJSON)),
        'links': PaginationLinksToJSON(value['links']),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

