/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Charge } from './Charge';
import {
    ChargeFromJSON,
    ChargeFromJSONTyped,
    ChargeToJSON,
    ChargeToJSONTyped,
} from './Charge';

/**
 * 
 * @export
 * @interface GetCharges200Response
 */
export interface GetCharges200Response {
    /**
     * 
     * @type {Array<Charge>}
     * @memberof GetCharges200Response
     */
    data?: Array<Charge>;
}

/**
 * Check if a given object implements the GetCharges200Response interface.
 */
export function instanceOfGetCharges200Response(value: object): value is GetCharges200Response {
    return true;
}

export function GetCharges200ResponseFromJSON(json: any): GetCharges200Response {
    return GetCharges200ResponseFromJSONTyped(json, false);
}

export function GetCharges200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCharges200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ChargeFromJSON)),
    };
}

export function GetCharges200ResponseToJSON(json: any): GetCharges200Response {
    return GetCharges200ResponseToJSONTyped(json, false);
}

export function GetCharges200ResponseToJSONTyped(value?: GetCharges200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ChargeToJSON)),
    };
}

