/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Class } from './Class';
import {
    instanceOfClass,
    ClassFromJSON,
    ClassFromJSONTyped,
    ClassToJSON,
} from './Class';
import type { Provider } from './Provider';
import {
    instanceOfProvider,
    ProviderFromJSON,
    ProviderFromJSONTyped,
    ProviderToJSON,
} from './Provider';

/**
 * @type GetDiscover200ResponseDataInner
 * 
 * @export
 */
export type GetDiscover200ResponseDataInner = { type: 'activity' } & Class | { type: 'provider' } & Provider;

export function GetDiscover200ResponseDataInnerFromJSON(json: any): GetDiscover200ResponseDataInner {
    return GetDiscover200ResponseDataInnerFromJSONTyped(json, false);
}

export function GetDiscover200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDiscover200ResponseDataInner {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'activity':
            return Object.assign({}, ClassFromJSONTyped(json, true), { type: 'activity' } as const);
        case 'provider':
            return Object.assign({}, ProviderFromJSONTyped(json, true), { type: 'provider' } as const);
        default:
            return json;
    }
}

export function GetDiscover200ResponseDataInnerToJSON(json: any): any {
    return GetDiscover200ResponseDataInnerToJSONTyped(json, false);
}

export function GetDiscover200ResponseDataInnerToJSONTyped(value?: GetDiscover200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'activity':
            return Object.assign({}, ClassToJSON(value), { type: 'activity' } as const);
        case 'provider':
            return Object.assign({}, ProviderToJSON(value), { type: 'provider' } as const);
        default:
            return value;
    }
}

