/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetDiscover200ResponseDataInner } from './GetDiscover200ResponseDataInner';
import {
    GetDiscover200ResponseDataInnerFromJSON,
    GetDiscover200ResponseDataInnerFromJSONTyped,
    GetDiscover200ResponseDataInnerToJSON,
    GetDiscover200ResponseDataInnerToJSONTyped,
} from './GetDiscover200ResponseDataInner';

/**
 * 
 * @export
 * @interface GetDiscover200Response
 */
export interface GetDiscover200Response {
    /**
     * 
     * @type {Array<GetDiscover200ResponseDataInner>}
     * @memberof GetDiscover200Response
     */
    data?: Array<GetDiscover200ResponseDataInner>;
}

/**
 * Check if a given object implements the GetDiscover200Response interface.
 */
export function instanceOfGetDiscover200Response(value: object): value is GetDiscover200Response {
    return true;
}

export function GetDiscover200ResponseFromJSON(json: any): GetDiscover200Response {
    return GetDiscover200ResponseFromJSONTyped(json, false);
}

export function GetDiscover200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDiscover200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GetDiscover200ResponseDataInnerFromJSON)),
    };
}

export function GetDiscover200ResponseToJSON(json: any): GetDiscover200Response {
    return GetDiscover200ResponseToJSONTyped(json, false);
}

export function GetDiscover200ResponseToJSONTyped(value?: GetDiscover200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GetDiscover200ResponseDataInnerToJSON)),
    };
}

