/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDiscoverFilterBoundsParameter
 */
export interface GetDiscoverFilterBoundsParameter {
    /**
     * 
     * @type {number}
     * @memberof GetDiscoverFilterBoundsParameter
     */
    north?: number;
    /**
     * 
     * @type {number}
     * @memberof GetDiscoverFilterBoundsParameter
     */
    south?: number;
    /**
     * 
     * @type {number}
     * @memberof GetDiscoverFilterBoundsParameter
     */
    east?: number;
    /**
     * 
     * @type {number}
     * @memberof GetDiscoverFilterBoundsParameter
     */
    west?: number;
}

/**
 * Check if a given object implements the GetDiscoverFilterBoundsParameter interface.
 */
export function instanceOfGetDiscoverFilterBoundsParameter(value: object): value is GetDiscoverFilterBoundsParameter {
    return true;
}

export function GetDiscoverFilterBoundsParameterFromJSON(json: any): GetDiscoverFilterBoundsParameter {
    return GetDiscoverFilterBoundsParameterFromJSONTyped(json, false);
}

export function GetDiscoverFilterBoundsParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDiscoverFilterBoundsParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'north': json['north'] == null ? undefined : json['north'],
        'south': json['south'] == null ? undefined : json['south'],
        'east': json['east'] == null ? undefined : json['east'],
        'west': json['west'] == null ? undefined : json['west'],
    };
}

export function GetDiscoverFilterBoundsParameterToJSON(json: any): GetDiscoverFilterBoundsParameter {
    return GetDiscoverFilterBoundsParameterToJSONTyped(json, false);
}

export function GetDiscoverFilterBoundsParameterToJSONTyped(value?: GetDiscoverFilterBoundsParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'north': value['north'],
        'south': value['south'],
        'east': value['east'],
        'west': value['west'],
    };
}

