/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface GetLink200Response
 */
export interface GetLink200Response {
    /**
     * 
     * @type {Link}
     * @memberof GetLink200Response
     */
    data?: Link;
}

/**
 * Check if a given object implements the GetLink200Response interface.
 */
export function instanceOfGetLink200Response(value: object): value is GetLink200Response {
    return true;
}

export function GetLink200ResponseFromJSON(json: any): GetLink200Response {
    return GetLink200ResponseFromJSONTyped(json, false);
}

export function GetLink200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLink200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : LinkFromJSON(json['data']),
    };
}

export function GetLink200ResponseToJSON(json: any): GetLink200Response {
    return GetLink200ResponseToJSONTyped(json, false);
}

export function GetLink200ResponseToJSONTyped(value?: GetLink200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': LinkToJSON(value['data']),
    };
}

