/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMetric200ResponseOneOf1
 */
export interface GetMetric200ResponseOneOf1 {
    /**
     * 
     * @type {number}
     * @memberof GetMetric200ResponseOneOf1
     */
    value?: number;
    /**
     * 
     * @type {number}
     * @memberof GetMetric200ResponseOneOf1
     */
    previous?: number;
}

/**
 * Check if a given object implements the GetMetric200ResponseOneOf1 interface.
 */
export function instanceOfGetMetric200ResponseOneOf1(value: object): value is GetMetric200ResponseOneOf1 {
    return true;
}

export function GetMetric200ResponseOneOf1FromJSON(json: any): GetMetric200ResponseOneOf1 {
    return GetMetric200ResponseOneOf1FromJSONTyped(json, false);
}

export function GetMetric200ResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMetric200ResponseOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'previous': json['previous'] == null ? undefined : json['previous'],
    };
}

export function GetMetric200ResponseOneOf1ToJSON(json: any): GetMetric200ResponseOneOf1 {
    return GetMetric200ResponseOneOf1ToJSONTyped(json, false);
}

export function GetMetric200ResponseOneOf1ToJSONTyped(value?: GetMetric200ResponseOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'previous': value['previous'],
    };
}

