/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetMetric200ResponseOneOfTrendInner } from './GetMetric200ResponseOneOfTrendInner';
import {
    GetMetric200ResponseOneOfTrendInnerFromJSON,
    GetMetric200ResponseOneOfTrendInnerFromJSONTyped,
    GetMetric200ResponseOneOfTrendInnerToJSON,
    GetMetric200ResponseOneOfTrendInnerToJSONTyped,
} from './GetMetric200ResponseOneOfTrendInner';

/**
 * 
 * @export
 * @interface GetMetric200ResponseOneOf
 */
export interface GetMetric200ResponseOneOf {
    /**
     * 
     * @type {Array<GetMetric200ResponseOneOfTrendInner>}
     * @memberof GetMetric200ResponseOneOf
     */
    trend?: Array<GetMetric200ResponseOneOfTrendInner>;
}

/**
 * Check if a given object implements the GetMetric200ResponseOneOf interface.
 */
export function instanceOfGetMetric200ResponseOneOf(value: object): value is GetMetric200ResponseOneOf {
    return true;
}

export function GetMetric200ResponseOneOfFromJSON(json: any): GetMetric200ResponseOneOf {
    return GetMetric200ResponseOneOfFromJSONTyped(json, false);
}

export function GetMetric200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMetric200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'trend': json['trend'] == null ? undefined : ((json['trend'] as Array<any>).map(GetMetric200ResponseOneOfTrendInnerFromJSON)),
    };
}

export function GetMetric200ResponseOneOfToJSON(json: any): GetMetric200ResponseOneOf {
    return GetMetric200ResponseOneOfToJSONTyped(json, false);
}

export function GetMetric200ResponseOneOfToJSONTyped(value?: GetMetric200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trend': value['trend'] == null ? undefined : ((value['trend'] as Array<any>).map(GetMetric200ResponseOneOfTrendInnerToJSON)),
    };
}

