/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';

/**
 * 
 * @export
 * @interface GetOrders200Response
 */
export interface GetOrders200Response {
    /**
     * 
     * @type {Array<Order>}
     * @memberof GetOrders200Response
     */
    data?: Array<Order>;
}

/**
 * Check if a given object implements the GetOrders200Response interface.
 */
export function instanceOfGetOrders200Response(value: object): value is GetOrders200Response {
    return true;
}

export function GetOrders200ResponseFromJSON(json: any): GetOrders200Response {
    return GetOrders200ResponseFromJSONTyped(json, false);
}

export function GetOrders200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrders200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(OrderFromJSON)),
    };
}

export function GetOrders200ResponseToJSON(json: any): GetOrders200Response {
    return GetOrders200ResponseToJSONTyped(json, false);
}

export function GetOrders200ResponseToJSONTyped(value?: GetOrders200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(OrderToJSON)),
    };
}

