/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';

/**
 * 
 * @export
 * @interface GetPrices200Response
 */
export interface GetPrices200Response {
    /**
     * 
     * @type {Array<Price>}
     * @memberof GetPrices200Response
     */
    data?: Array<Price>;
}

/**
 * Check if a given object implements the GetPrices200Response interface.
 */
export function instanceOfGetPrices200Response(value: object): value is GetPrices200Response {
    return true;
}

export function GetPrices200ResponseFromJSON(json: any): GetPrices200Response {
    return GetPrices200ResponseFromJSONTyped(json, false);
}

export function GetPrices200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPrices200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PriceFromJSON)),
    };
}

export function GetPrices200ResponseToJSON(json: any): GetPrices200Response {
    return GetPrices200ResponseToJSONTyped(json, false);
}

export function GetPrices200ResponseToJSONTyped(value?: GetPrices200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PriceToJSON)),
    };
}

