/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
    SubscriptionToJSONTyped,
} from './Subscription';

/**
 * 
 * @export
 * @interface GetSubscriptions200Response
 */
export interface GetSubscriptions200Response {
    /**
     * 
     * @type {Array<Subscription>}
     * @memberof GetSubscriptions200Response
     */
    data?: Array<Subscription>;
}

/**
 * Check if a given object implements the GetSubscriptions200Response interface.
 */
export function instanceOfGetSubscriptions200Response(value: object): value is GetSubscriptions200Response {
    return true;
}

export function GetSubscriptions200ResponseFromJSON(json: any): GetSubscriptions200Response {
    return GetSubscriptions200ResponseFromJSONTyped(json, false);
}

export function GetSubscriptions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscriptions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SubscriptionFromJSON)),
    };
}

export function GetSubscriptions200ResponseToJSON(json: any): GetSubscriptions200Response {
    return GetSubscriptions200ResponseToJSONTyped(json, false);
}

export function GetSubscriptions200ResponseToJSONTyped(value?: GetSubscriptions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SubscriptionToJSON)),
    };
}

