/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Stage } from './Stage';
import {
    StageFromJSON,
    StageFromJSONTyped,
    StageToJSON,
    StageToJSONTyped,
} from './Stage';

/**
 * 
 * @export
 * @interface GetStages200Response
 */
export interface GetStages200Response {
    /**
     * 
     * @type {Array<Stage>}
     * @memberof GetStages200Response
     */
    data?: Array<Stage>;
}

/**
 * Check if a given object implements the GetStages200Response interface.
 */
export function instanceOfGetStages200Response(value: object): value is GetStages200Response {
    return true;
}

export function GetStages200ResponseFromJSON(json: any): GetStages200Response {
    return GetStages200ResponseFromJSONTyped(json, false);
}

export function GetStages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StageFromJSON)),
    };
}

export function GetStages200ResponseToJSON(json: any): GetStages200Response {
    return GetStages200ResponseToJSONTyped(json, false);
}

export function GetStages200ResponseToJSONTyped(value?: GetStages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StageToJSON)),
    };
}

