/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudentStage } from './StudentStage';
import {
    StudentStageFromJSON,
    StudentStageFromJSONTyped,
    StudentStageToJSON,
    StudentStageToJSONTyped,
} from './StudentStage';

/**
 * 
 * @export
 * @interface GetStudentStages200Response
 */
export interface GetStudentStages200Response {
    /**
     * 
     * @type {Array<StudentStage>}
     * @memberof GetStudentStages200Response
     */
    data?: Array<StudentStage>;
}

/**
 * Check if a given object implements the GetStudentStages200Response interface.
 */
export function instanceOfGetStudentStages200Response(value: object): value is GetStudentStages200Response {
    return true;
}

export function GetStudentStages200ResponseFromJSON(json: any): GetStudentStages200Response {
    return GetStudentStages200ResponseFromJSONTyped(json, false);
}

export function GetStudentStages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStudentStages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StudentStageFromJSON)),
    };
}

export function GetStudentStages200ResponseToJSON(json: any): GetStudentStages200Response {
    return GetStudentStages200ResponseToJSONTyped(json, false);
}

export function GetStudentStages200ResponseToJSONTyped(value?: GetStudentStages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StudentStageToJSON)),
    };
}

