/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Venue } from './Venue';
import {
    VenueFromJSON,
    VenueFromJSONTyped,
    VenueToJSON,
    VenueToJSONTyped,
} from './Venue';

/**
 * 
 * @export
 * @interface GetVenue200Response
 */
export interface GetVenue200Response {
    /**
     * 
     * @type {Venue}
     * @memberof GetVenue200Response
     */
    data?: Venue;
}

/**
 * Check if a given object implements the GetVenue200Response interface.
 */
export function instanceOfGetVenue200Response(value: object): value is GetVenue200Response {
    return true;
}

export function GetVenue200ResponseFromJSON(json: any): GetVenue200Response {
    return GetVenue200ResponseFromJSONTyped(json, false);
}

export function GetVenue200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVenue200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : VenueFromJSON(json['data']),
    };
}

export function GetVenue200ResponseToJSON(json: any): GetVenue200Response {
    return GetVenue200ResponseToJSONTyped(json, false);
}

export function GetVenue200ResponseToJSONTyped(value?: GetVenue200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': VenueToJSON(value['data']),
    };
}

