/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Link
 */
export interface Link {
    /**
     * 
     * @type {number}
     * @memberof Link
     */
    providerId?: number;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    providerName?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    stripeId?: string;
    /**
     * 
     * @type {number}
     * @memberof Link
     */
    balance?: number;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    cardLastFour?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    bacsLastFour?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Link
     */
    marketingConsent?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Link
     */
    photoConsent?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Link
     */
    sessionReminders?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Link
     */
    connectedAt?: Date;
}

/**
 * Check if a given object implements the Link interface.
 */
export function instanceOfLink(value: object): value is Link {
    return true;
}

export function LinkFromJSON(json: any): Link {
    return LinkFromJSONTyped(json, false);
}

export function LinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Link {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['provider_id'] == null ? undefined : json['provider_id'],
        'providerName': json['provider_name'] == null ? undefined : json['provider_name'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'userName': json['user_name'] == null ? undefined : json['user_name'],
        'stripeId': json['stripe_id'] == null ? undefined : json['stripe_id'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'cardLastFour': json['card_last_four'] == null ? undefined : json['card_last_four'],
        'bacsLastFour': json['bacs_last_four'] == null ? undefined : json['bacs_last_four'],
        'marketingConsent': json['marketing_consent'] == null ? undefined : json['marketing_consent'],
        'photoConsent': json['photo_consent'] == null ? undefined : json['photo_consent'],
        'sessionReminders': json['session_reminders'] == null ? undefined : json['session_reminders'],
        'connectedAt': json['connected_at'] == null ? undefined : (new Date(json['connected_at'])),
    };
}

export function LinkToJSON(json: any): Link {
    return LinkToJSONTyped(json, false);
}

export function LinkToJSONTyped(value?: Link | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_id': value['providerId'],
        'provider_name': value['providerName'],
        'user_id': value['userId'],
        'user_name': value['userName'],
        'stripe_id': value['stripeId'],
        'balance': value['balance'],
        'card_last_four': value['cardLastFour'],
        'bacs_last_four': value['bacsLastFour'],
        'marketing_consent': value['marketingConsent'],
        'photo_consent': value['photoConsent'],
        'session_reminders': value['sessionReminders'],
        'connected_at': value['connectedAt'] == null ? undefined : ((value['connectedAt']).toISOString()),
    };
}

