/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMetaLink
 */
export interface PaginationMetaLink {
    /**
     * 
     * @type {string}
     * @memberof PaginationMetaLink
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginationMetaLink
     */
    label?: string;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetaLink
     */
    page?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationMetaLink
     */
    active?: boolean;
}

/**
 * Check if a given object implements the PaginationMetaLink interface.
 */
export function instanceOfPaginationMetaLink(value: object): value is PaginationMetaLink {
    return true;
}

export function PaginationMetaLinkFromJSON(json: any): PaginationMetaLink {
    return PaginationMetaLinkFromJSONTyped(json, false);
}

export function PaginationMetaLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMetaLink {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'label': json['label'] == null ? undefined : json['label'],
        'page': json['page'] == null ? undefined : json['page'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function PaginationMetaLinkToJSON(json: any): PaginationMetaLink {
    return PaginationMetaLinkToJSONTyped(json, false);
}

export function PaginationMetaLinkToJSONTyped(value?: PaginationMetaLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'label': value['label'],
        'page': value['page'],
        'active': value['active'],
    };
}

