/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMetaLink } from './PaginationMetaLink';
import {
    PaginationMetaLinkFromJSON,
    PaginationMetaLinkFromJSONTyped,
    PaginationMetaLinkToJSON,
    PaginationMetaLinkToJSONTyped,
} from './PaginationMetaLink';

/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    from?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    lastPage?: number;
    /**
     * 
     * @type {Array<PaginationMetaLink>}
     * @memberof PaginationMeta
     */
    links?: Array<PaginationMetaLink>;
    /**
     * 
     * @type {string}
     * @memberof PaginationMeta
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    to?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    total?: number;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): value is PaginationMeta {
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'] == null ? undefined : json['current_page'],
        'from': json['from'] == null ? undefined : json['from'],
        'lastPage': json['last_page'] == null ? undefined : json['last_page'],
        'links': json['links'] == null ? undefined : ((json['links'] as Array<any>).map(PaginationMetaLinkFromJSON)),
        'path': json['path'] == null ? undefined : json['path'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'to': json['to'] == null ? undefined : json['to'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
    return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(value?: PaginationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'from': value['from'],
        'last_page': value['lastPage'],
        'links': value['links'] == null ? undefined : ((value['links'] as Array<any>).map(PaginationMetaLinkToJSON)),
        'path': value['path'],
        'per_page': value['perPage'],
        'to': value['to'],
        'total': value['total'],
    };
}

