/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchPasswordRequest
 */
export interface PatchPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchPasswordRequest
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPasswordRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPasswordRequest
     */
    newPasswordConfirmation: string;
}

/**
 * Check if a given object implements the PatchPasswordRequest interface.
 */
export function instanceOfPatchPasswordRequest(value: object): value is PatchPasswordRequest {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('newPasswordConfirmation' in value) || value['newPasswordConfirmation'] === undefined) return false;
    return true;
}

export function PatchPasswordRequestFromJSON(json: any): PatchPasswordRequest {
    return PatchPasswordRequestFromJSONTyped(json, false);
}

export function PatchPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['current_password'],
        'newPassword': json['new_password'],
        'newPasswordConfirmation': json['new_password_confirmation'],
    };
}

export function PatchPasswordRequestToJSON(json: any): PatchPasswordRequest {
    return PatchPasswordRequestToJSONTyped(json, false);
}

export function PatchPasswordRequestToJSONTyped(value?: PatchPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
        'new_password_confirmation': value['newPasswordConfirmation'],
    };
}

