/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchDetailsRequest
 */
export interface PatchDetailsRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchDetailsRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof PatchDetailsRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof PatchDetailsRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PatchDetailsRequest
     */
    telephone: string;
    /**
     * 
     * @type {string}
     * @memberof PatchDetailsRequest
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchDetailsRequest
     */
    town?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchDetailsRequest
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchDetailsRequest
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchDetailsRequest
     */
    medical?: string;
}

/**
 * Check if a given object implements the PatchDetailsRequest interface.
 */
export function instanceOfPatchDetailsRequest(value: object): value is PatchDetailsRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('telephone' in value) || value['telephone'] === undefined) return false;
    return true;
}

export function PatchDetailsRequestFromJSON(json: any): PatchDetailsRequest {
    return PatchDetailsRequestFromJSONTyped(json, false);
}

export function PatchDetailsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchDetailsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'email': json['email'],
        'telephone': json['telephone'],
        'street': json['street'] == null ? undefined : json['street'],
        'town': json['town'] == null ? undefined : json['town'],
        'region': json['region'] == null ? undefined : json['region'],
        'postcode': json['postcode'] == null ? undefined : json['postcode'],
        'medical': json['medical'] == null ? undefined : json['medical'],
    };
}

export function PatchDetailsRequestToJSON(json: any): PatchDetailsRequest {
    return PatchDetailsRequestToJSONTyped(json, false);
}

export function PatchDetailsRequestToJSONTyped(value?: PatchDetailsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'telephone': value['telephone'],
        'street': value['street'],
        'town': value['town'],
        'region': value['region'],
        'postcode': value['postcode'],
        'medical': value['medical'],
    };
}

