/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchStudentRequest
 */
export interface PatchStudentRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchStudentRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof PatchStudentRequest
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchStudentRequest
     */
    dob?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchStudentRequest
     */
    medical?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchStudentRequest
     */
    relation?: string;
}

/**
 * Check if a given object implements the PatchStudentRequest interface.
 */
export function instanceOfPatchStudentRequest(value: object): value is PatchStudentRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function PatchStudentRequestFromJSON(json: any): PatchStudentRequest {
    return PatchStudentRequestFromJSONTyped(json, false);
}

export function PatchStudentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchStudentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'dob': json['dob'] == null ? undefined : (new Date(json['dob'])),
        'medical': json['medical'] == null ? undefined : json['medical'],
        'relation': json['relation'] == null ? undefined : json['relation'],
    };
}

export function PatchStudentRequestToJSON(json: any): PatchStudentRequest {
    return PatchStudentRequestToJSONTyped(json, false);
}

export function PatchStudentRequestToJSONTyped(value?: PatchStudentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'dob': value['dob'] == null ? undefined : ((value['dob']).toISOString().substring(0,10)),
        'medical': value['medical'],
        'relation': value['relation'],
    };
}

