/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchMarketingConsentRequest
 */
export interface PatchMarketingConsentRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchMarketingConsentRequest
     */
    providerId: number;
}

/**
 * Check if a given object implements the PatchMarketingConsentRequest interface.
 */
export function instanceOfPatchMarketingConsentRequest(value: object): value is PatchMarketingConsentRequest {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    return true;
}

export function PatchMarketingConsentRequestFromJSON(json: any): PatchMarketingConsentRequest {
    return PatchMarketingConsentRequestFromJSONTyped(json, false);
}

export function PatchMarketingConsentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchMarketingConsentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['provider_id'],
    };
}

export function PatchMarketingConsentRequestToJSON(json: any): PatchMarketingConsentRequest {
    return PatchMarketingConsentRequestToJSONTyped(json, false);
}

export function PatchMarketingConsentRequestToJSONTyped(value?: PatchMarketingConsentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_id': value['providerId'],
    };
}

