/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';
import type { Booking } from './Booking';
import {
    BookingFromJSON,
    BookingFromJSONTyped,
    BookingToJSON,
    BookingToJSONTyped,
} from './Booking';
import type { Student } from './Student';
import {
    StudentFromJSON,
    StudentFromJSONTyped,
    StudentToJSON,
    StudentToJSONTyped,
} from './Student';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
    SubscriptionToJSONTyped,
} from './Subscription';

/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    paymentDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    status?: PaymentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    providerName?: string;
    /**
     * 
     * @type {Booking}
     * @memberof Payment
     */
    booking?: Booking;
    /**
     * 
     * @type {Order}
     * @memberof Payment
     */
    order?: Order;
    /**
     * 
     * @type {Student}
     * @memberof Payment
     */
    student?: Student;
    /**
     * 
     * @type {Subscription}
     * @memberof Payment
     */
    subscription?: Subscription;
}


/**
 * @export
 */
export const PaymentStatusEnum = {
    Successful: 'Successful',
    Failed: 'Failed',
    Refunded: 'Refunded'
} as const;
export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];


/**
 * Check if a given object implements the Payment interface.
 */
export function instanceOfPayment(value: object): value is Payment {
    return true;
}

export function PaymentFromJSON(json: any): Payment {
    return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'paymentDate': json['payment_date'] == null ? undefined : (new Date(json['payment_date'])),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'status': json['status'] == null ? undefined : json['status'],
        'providerName': json['provider_name'] == null ? undefined : json['provider_name'],
        'booking': json['booking'] == null ? undefined : BookingFromJSON(json['booking']),
        'order': json['order'] == null ? undefined : OrderFromJSON(json['order']),
        'student': json['student'] == null ? undefined : StudentFromJSON(json['student']),
        'subscription': json['subscription'] == null ? undefined : SubscriptionFromJSON(json['subscription']),
    };
}

export function PaymentToJSON(json: any): Payment {
    return PaymentToJSONTyped(json, false);
}

export function PaymentToJSONTyped(value?: Payment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'payment_date': value['paymentDate'] == null ? undefined : ((value['paymentDate']).toISOString()),
        'amount': value['amount'],
        'status': value['status'],
        'provider_name': value['providerName'],
        'booking': BookingToJSON(value['booking']),
        'order': OrderToJSON(value['order']),
        'student': StudentToJSON(value['student']),
        'subscription': SubscriptionToJSON(value['subscription']),
    };
}

