/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhotoConsentContent
 */
export interface PhotoConsentContent {
    /**
     * 
     * @type {string}
     * @memberof PhotoConsentContent
     */
    content: string;
}

/**
 * Check if a given object implements the PhotoConsentContent interface.
 */
export function instanceOfPhotoConsentContent(value: object): value is PhotoConsentContent {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function PhotoConsentContentFromJSON(json: any): PhotoConsentContent {
    return PhotoConsentContentFromJSONTyped(json, false);
}

export function PhotoConsentContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhotoConsentContent {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function PhotoConsentContentToJSON(json: any): PhotoConsentContent {
    return PhotoConsentContentToJSONTyped(json, false);
}

export function PhotoConsentContentToJSONTyped(value?: PhotoConsentContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

