/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhotoConsentLink
 */
export interface PhotoConsentLink {
    /**
     * 
     * @type {string}
     * @memberof PhotoConsentLink
     */
    link: string;
}

/**
 * Check if a given object implements the PhotoConsentLink interface.
 */
export function instanceOfPhotoConsentLink(value: object): value is PhotoConsentLink {
    if (!('link' in value) || value['link'] === undefined) return false;
    return true;
}

export function PhotoConsentLinkFromJSON(json: any): PhotoConsentLink {
    return PhotoConsentLinkFromJSONTyped(json, false);
}

export function PhotoConsentLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhotoConsentLink {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'],
    };
}

export function PhotoConsentLinkToJSON(json: any): PhotoConsentLink {
    return PhotoConsentLinkToJSONTyped(json, false);
}

export function PhotoConsentLinkToJSONTyped(value?: PhotoConsentLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
    };
}

