/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Plan
 */
export interface Plan {
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    net: number;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    gross: number;
}

/**
 * Check if a given object implements the Plan interface.
 */
export function instanceOfPlan(value: object): value is Plan {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('net' in value) || value['net'] === undefined) return false;
    if (!('gross' in value) || value['gross'] === undefined) return false;
    return true;
}

export function PlanFromJSON(json: any): Plan {
    return PlanFromJSONTyped(json, false);
}

export function PlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'net': json['net'],
        'gross': json['gross'],
    };
}

export function PlanToJSON(json: any): Plan {
    return PlanToJSONTyped(json, false);
}

export function PlanToJSONTyped(value?: Plan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'net': value['net'],
        'gross': value['gross'],
    };
}

