/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPayBookingRequest
 */
export interface PostPayBookingRequest {
    /**
     * 
     * @type {string}
     * @memberof PostPayBookingRequest
     */
    paymentIntent?: string;
    /**
     * 
     * @type {number}
     * @memberof PostPayBookingRequest
     */
    creditAmount?: number;
}

/**
 * Check if a given object implements the PostPayBookingRequest interface.
 */
export function instanceOfPostPayBookingRequest(value: object): value is PostPayBookingRequest {
    return true;
}

export function PostPayBookingRequestFromJSON(json: any): PostPayBookingRequest {
    return PostPayBookingRequestFromJSONTyped(json, false);
}

export function PostPayBookingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPayBookingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentIntent': json['payment_intent'] == null ? undefined : json['payment_intent'],
        'creditAmount': json['credit_amount'] == null ? undefined : json['credit_amount'],
    };
}

export function PostPayBookingRequestToJSON(json: any): PostPayBookingRequest {
    return PostPayBookingRequestToJSONTyped(json, false);
}

export function PostPayBookingRequestToJSONTyped(value?: PostPayBookingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_intent': value['paymentIntent'],
        'credit_amount': value['creditAmount'],
    };
}

