/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApplyCouponRequest
 */
export interface PostApplyCouponRequest {
    /**
     * 
     * @type {number}
     * @memberof PostApplyCouponRequest
     */
    _class?: number;
    /**
     * 
     * @type {string}
     * @memberof PostApplyCouponRequest
     */
    code?: string;
}

/**
 * Check if a given object implements the PostApplyCouponRequest interface.
 */
export function instanceOfPostApplyCouponRequest(value: object): value is PostApplyCouponRequest {
    return true;
}

export function PostApplyCouponRequestFromJSON(json: any): PostApplyCouponRequest {
    return PostApplyCouponRequestFromJSONTyped(json, false);
}

export function PostApplyCouponRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApplyCouponRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '_class': json['class'] == null ? undefined : json['class'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function PostApplyCouponRequestToJSON(json: any): PostApplyCouponRequest {
    return PostApplyCouponRequestToJSONTyped(json, false);
}

export function PostApplyCouponRequestToJSONTyped(value?: PostApplyCouponRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'class': value['_class'],
        'code': value['code'],
    };
}

