/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostBookCatchUpRequest
 */
export interface PostBookCatchUpRequest {
    /**
     * 
     * @type {number}
     * @memberof PostBookCatchUpRequest
     */
    bankedSessionId?: number;
    /**
     * 
     * @type {number}
     * @memberof PostBookCatchUpRequest
     */
    sessionId?: number;
}

/**
 * Check if a given object implements the PostBookCatchUpRequest interface.
 */
export function instanceOfPostBookCatchUpRequest(value: object): value is PostBookCatchUpRequest {
    return true;
}

export function PostBookCatchUpRequestFromJSON(json: any): PostBookCatchUpRequest {
    return PostBookCatchUpRequestFromJSONTyped(json, false);
}

export function PostBookCatchUpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostBookCatchUpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bankedSessionId': json['banked_session_id'] == null ? undefined : json['banked_session_id'],
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
    };
}

export function PostBookCatchUpRequestToJSON(json: any): PostBookCatchUpRequest {
    return PostBookCatchUpRequestToJSONTyped(json, false);
}

export function PostBookCatchUpRequestToJSONTyped(value?: PostBookCatchUpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'banked_session_id': value['bankedSessionId'],
        'session_id': value['sessionId'],
    };
}

