/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudentGoal } from './StudentGoal';
import {
    StudentGoalFromJSON,
    StudentGoalFromJSONTyped,
    StudentGoalToJSON,
    StudentGoalToJSONTyped,
} from './StudentGoal';

/**
 * 
 * @export
 * @interface PostStudentGoalStatus200Response
 */
export interface PostStudentGoalStatus200Response {
    /**
     * 
     * @type {StudentGoal}
     * @memberof PostStudentGoalStatus200Response
     */
    data?: StudentGoal;
}

/**
 * Check if a given object implements the PostStudentGoalStatus200Response interface.
 */
export function instanceOfPostStudentGoalStatus200Response(value: object): value is PostStudentGoalStatus200Response {
    return true;
}

export function PostStudentGoalStatus200ResponseFromJSON(json: any): PostStudentGoalStatus200Response {
    return PostStudentGoalStatus200ResponseFromJSONTyped(json, false);
}

export function PostStudentGoalStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostStudentGoalStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : StudentGoalFromJSON(json['data']),
    };
}

export function PostStudentGoalStatus200ResponseToJSON(json: any): PostStudentGoalStatus200Response {
    return PostStudentGoalStatus200ResponseToJSONTyped(json, false);
}

export function PostStudentGoalStatus200ResponseToJSONTyped(value?: PostStudentGoalStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': StudentGoalToJSON(value['data']),
    };
}

