/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Voucher } from './Voucher';
import {
    VoucherFromJSON,
    VoucherFromJSONTyped,
    VoucherToJSON,
    VoucherToJSONTyped,
} from './Voucher';

/**
 * 
 * @export
 * @interface PostVoucher200Response
 */
export interface PostVoucher200Response {
    /**
     * 
     * @type {Voucher}
     * @memberof PostVoucher200Response
     */
    data?: Voucher;
}

/**
 * Check if a given object implements the PostVoucher200Response interface.
 */
export function instanceOfPostVoucher200Response(value: object): value is PostVoucher200Response {
    return true;
}

export function PostVoucher200ResponseFromJSON(json: any): PostVoucher200Response {
    return PostVoucher200ResponseFromJSONTyped(json, false);
}

export function PostVoucher200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostVoucher200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : VoucherFromJSON(json['data']),
    };
}

export function PostVoucher200ResponseToJSON(json: any): PostVoucher200Response {
    return PostVoucher200ResponseToJSONTyped(json, false);
}

export function PostVoucher200ResponseToJSONTyped(value?: PostVoucher200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': VoucherToJSON(value['data']),
    };
}

