/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostVoucherCheck200Response
 */
export interface PostVoucherCheck200Response {
    /**
     * 
     * @type {string}
     * @memberof PostVoucherCheck200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostVoucherCheck200Response interface.
 */
export function instanceOfPostVoucherCheck200Response(value: object): value is PostVoucherCheck200Response {
    return true;
}

export function PostVoucherCheck200ResponseFromJSON(json: any): PostVoucherCheck200Response {
    return PostVoucherCheck200ResponseFromJSONTyped(json, false);
}

export function PostVoucherCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostVoucherCheck200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostVoucherCheck200ResponseToJSON(json: any): PostVoucherCheck200Response {
    return PostVoucherCheck200ResponseToJSONTyped(json, false);
}

export function PostVoucherCheck200ResponseToJSONTyped(value?: PostVoucherCheck200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

