/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPaySubscriptionRequest
 */
export interface PostPaySubscriptionRequest {
    /**
     * 
     * @type {string}
     * @memberof PostPaySubscriptionRequest
     */
    paymentIntent?: string;
}

/**
 * Check if a given object implements the PostPaySubscriptionRequest interface.
 */
export function instanceOfPostPaySubscriptionRequest(value: object): value is PostPaySubscriptionRequest {
    return true;
}

export function PostPaySubscriptionRequestFromJSON(json: any): PostPaySubscriptionRequest {
    return PostPaySubscriptionRequestFromJSONTyped(json, false);
}

export function PostPaySubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPaySubscriptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentIntent': json['payment_intent'] == null ? undefined : json['payment_intent'],
    };
}

export function PostPaySubscriptionRequestToJSON(json: any): PostPaySubscriptionRequest {
    return PostPaySubscriptionRequestToJSONTyped(json, false);
}

export function PostPaySubscriptionRequestToJSONTyped(value?: PostPaySubscriptionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_intent': value['paymentIntent'],
    };
}

