/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAttachPaymentMethodRequest
 */
export interface PostAttachPaymentMethodRequest {
    /**
     * 
     * @type {number}
     * @memberof PostAttachPaymentMethodRequest
     */
    providerId: number;
    /**
     * 
     * @type {string}
     * @memberof PostAttachPaymentMethodRequest
     */
    paymentMethod: string;
}

/**
 * Check if a given object implements the PostAttachPaymentMethodRequest interface.
 */
export function instanceOfPostAttachPaymentMethodRequest(value: object): value is PostAttachPaymentMethodRequest {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function PostAttachPaymentMethodRequestFromJSON(json: any): PostAttachPaymentMethodRequest {
    return PostAttachPaymentMethodRequestFromJSONTyped(json, false);
}

export function PostAttachPaymentMethodRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAttachPaymentMethodRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['provider_id'],
        'paymentMethod': json['payment_method'],
    };
}

export function PostAttachPaymentMethodRequestToJSON(json: any): PostAttachPaymentMethodRequest {
    return PostAttachPaymentMethodRequestToJSONTyped(json, false);
}

export function PostAttachPaymentMethodRequestToJSONTyped(value?: PostAttachPaymentMethodRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_id': value['providerId'],
        'payment_method': value['paymentMethod'],
    };
}

