/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostStudentGoalRequest
 */
export interface PostStudentGoalRequest {
    /**
     * 
     * @type {number}
     * @memberof PostStudentGoalRequest
     */
    goalId: number;
}

/**
 * Check if a given object implements the PostStudentGoalRequest interface.
 */
export function instanceOfPostStudentGoalRequest(value: object): value is PostStudentGoalRequest {
    if (!('goalId' in value) || value['goalId'] === undefined) return false;
    return true;
}

export function PostStudentGoalRequestFromJSON(json: any): PostStudentGoalRequest {
    return PostStudentGoalRequestFromJSONTyped(json, false);
}

export function PostStudentGoalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostStudentGoalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'goalId': json['goal_id'],
    };
}

export function PostStudentGoalRequestToJSON(json: any): PostStudentGoalRequest {
    return PostStudentGoalRequestToJSONTyped(json, false);
}

export function PostStudentGoalRequestToJSONTyped(value?: PostStudentGoalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'goal_id': value['goalId'],
    };
}

