/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSetupIntent200Response
 */
export interface PostSetupIntent200Response {
    /**
     * 
     * @type {string}
     * @memberof PostSetupIntent200Response
     */
    clientSecret?: string;
}

/**
 * Check if a given object implements the PostSetupIntent200Response interface.
 */
export function instanceOfPostSetupIntent200Response(value: object): value is PostSetupIntent200Response {
    return true;
}

export function PostSetupIntent200ResponseFromJSON(json: any): PostSetupIntent200Response {
    return PostSetupIntent200ResponseFromJSONTyped(json, false);
}

export function PostSetupIntent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSetupIntent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'clientSecret': json['client_secret'] == null ? undefined : json['client_secret'],
    };
}

export function PostSetupIntent200ResponseToJSON(json: any): PostSetupIntent200Response {
    return PostSetupIntent200ResponseToJSONTyped(json, false);
}

export function PostSetupIntent200ResponseToJSONTyped(value?: PostSetupIntent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_secret': value['clientSecret'],
    };
}

