/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudentGoalStatus } from './StudentGoalStatus';
import {
    StudentGoalStatusFromJSON,
    StudentGoalStatusFromJSONTyped,
    StudentGoalStatusToJSON,
    StudentGoalStatusToJSONTyped,
} from './StudentGoalStatus';

/**
 * 
 * @export
 * @interface PostStudentGoalStatusRequest
 */
export interface PostStudentGoalStatusRequest {
    /**
     * 
     * @type {StudentGoalStatus}
     * @memberof PostStudentGoalStatusRequest
     */
    status: StudentGoalStatus;
    /**
     * 
     * @type {number}
     * @memberof PostStudentGoalStatusRequest
     */
    bookingId?: number;
}



/**
 * Check if a given object implements the PostStudentGoalStatusRequest interface.
 */
export function instanceOfPostStudentGoalStatusRequest(value: object): value is PostStudentGoalStatusRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PostStudentGoalStatusRequestFromJSON(json: any): PostStudentGoalStatusRequest {
    return PostStudentGoalStatusRequestFromJSONTyped(json, false);
}

export function PostStudentGoalStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostStudentGoalStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StudentGoalStatusFromJSON(json['status']),
        'bookingId': json['booking_id'] == null ? undefined : json['booking_id'],
    };
}

export function PostStudentGoalStatusRequestToJSON(json: any): PostStudentGoalStatusRequest {
    return PostStudentGoalStatusRequestToJSONTyped(json, false);
}

export function PostStudentGoalStatusRequestToJSONTyped(value?: PostStudentGoalStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StudentGoalStatusToJSON(value['status']),
        'booking_id': value['bookingId'],
    };
}

