/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostApplyCoupon200ResponseMeta } from './PostApplyCoupon200ResponseMeta';
import {
    PostApplyCoupon200ResponseMetaFromJSON,
    PostApplyCoupon200ResponseMetaFromJSONTyped,
    PostApplyCoupon200ResponseMetaToJSON,
    PostApplyCoupon200ResponseMetaToJSONTyped,
} from './PostApplyCoupon200ResponseMeta';
import type { PostApplyCoupon200ResponseData } from './PostApplyCoupon200ResponseData';
import {
    PostApplyCoupon200ResponseDataFromJSON,
    PostApplyCoupon200ResponseDataFromJSONTyped,
    PostApplyCoupon200ResponseDataToJSON,
    PostApplyCoupon200ResponseDataToJSONTyped,
} from './PostApplyCoupon200ResponseData';

/**
 * 
 * @export
 * @interface PostApplyCoupon200Response
 */
export interface PostApplyCoupon200Response {
    /**
     * 
     * @type {PostApplyCoupon200ResponseData}
     * @memberof PostApplyCoupon200Response
     */
    data?: PostApplyCoupon200ResponseData;
    /**
     * 
     * @type {PostApplyCoupon200ResponseMeta}
     * @memberof PostApplyCoupon200Response
     */
    meta?: PostApplyCoupon200ResponseMeta;
}

/**
 * Check if a given object implements the PostApplyCoupon200Response interface.
 */
export function instanceOfPostApplyCoupon200Response(value: object): value is PostApplyCoupon200Response {
    return true;
}

export function PostApplyCoupon200ResponseFromJSON(json: any): PostApplyCoupon200Response {
    return PostApplyCoupon200ResponseFromJSONTyped(json, false);
}

export function PostApplyCoupon200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApplyCoupon200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PostApplyCoupon200ResponseDataFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : PostApplyCoupon200ResponseMetaFromJSON(json['meta']),
    };
}

export function PostApplyCoupon200ResponseToJSON(json: any): PostApplyCoupon200Response {
    return PostApplyCoupon200ResponseToJSONTyped(json, false);
}

export function PostApplyCoupon200ResponseToJSONTyped(value?: PostApplyCoupon200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PostApplyCoupon200ResponseDataToJSON(value['data']),
        'meta': PostApplyCoupon200ResponseMetaToJSON(value['meta']),
    };
}

