/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Waitee } from './Waitee';
import {
    WaiteeFromJSON,
    WaiteeFromJSONTyped,
    WaiteeToJSON,
    WaiteeToJSONTyped,
} from './Waitee';

/**
 * 
 * @export
 * @interface PostWaitee200Response
 */
export interface PostWaitee200Response {
    /**
     * 
     * @type {Array<Waitee>}
     * @memberof PostWaitee200Response
     */
    data?: Array<Waitee>;
}

/**
 * Check if a given object implements the PostWaitee200Response interface.
 */
export function instanceOfPostWaitee200Response(value: object): value is PostWaitee200Response {
    return true;
}

export function PostWaitee200ResponseFromJSON(json: any): PostWaitee200Response {
    return PostWaitee200ResponseFromJSONTyped(json, false);
}

export function PostWaitee200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWaitee200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(WaiteeFromJSON)),
    };
}

export function PostWaitee200ResponseToJSON(json: any): PostWaitee200Response {
    return PostWaitee200ResponseToJSONTyped(json, false);
}

export function PostWaitee200ResponseToJSONTyped(value?: PostWaitee200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(WaiteeToJSON)),
    };
}

