/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostStudentStageRequest
 */
export interface PostStudentStageRequest {
    /**
     * 
     * @type {number}
     * @memberof PostStudentStageRequest
     */
    stageId: number;
    /**
     * 
     * @type {string}
     * @memberof PostStudentStageRequest
     */
    awardedOn?: string;
}

/**
 * Check if a given object implements the PostStudentStageRequest interface.
 */
export function instanceOfPostStudentStageRequest(value: object): value is PostStudentStageRequest {
    if (!('stageId' in value) || value['stageId'] === undefined) return false;
    return true;
}

export function PostStudentStageRequestFromJSON(json: any): PostStudentStageRequest {
    return PostStudentStageRequestFromJSONTyped(json, false);
}

export function PostStudentStageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostStudentStageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'stageId': json['stage_id'],
        'awardedOn': json['awarded_on'] == null ? undefined : json['awarded_on'],
    };
}

export function PostStudentStageRequestToJSON(json: any): PostStudentStageRequest {
    return PostStudentStageRequestToJSONTyped(json, false);
}

export function PostStudentStageRequestToJSONTyped(value?: PostStudentStageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stage_id': value['stageId'],
        'awarded_on': value['awardedOn'],
    };
}

