/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostActivateRequest
 */
export interface PostActivateRequest {
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof PostActivateRequest
     */
    terms?: { [key: string]: boolean; };
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof PostActivateRequest
     */
    marketing?: { [key: string]: boolean; };
}

/**
 * Check if a given object implements the PostActivateRequest interface.
 */
export function instanceOfPostActivateRequest(value: object): value is PostActivateRequest {
    return true;
}

export function PostActivateRequestFromJSON(json: any): PostActivateRequest {
    return PostActivateRequestFromJSONTyped(json, false);
}

export function PostActivateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostActivateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'terms': json['terms'] == null ? undefined : json['terms'],
        'marketing': json['marketing'] == null ? undefined : json['marketing'],
    };
}

export function PostActivateRequestToJSON(json: any): PostActivateRequest {
    return PostActivateRequestToJSONTyped(json, false);
}

export function PostActivateRequestToJSONTyped(value?: PostActivateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'terms': value['terms'],
        'marketing': value['marketing'],
    };
}

