/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostPaymentIntentRequestOverrides } from './PostPaymentIntentRequestOverrides';
import {
    PostPaymentIntentRequestOverridesFromJSON,
    PostPaymentIntentRequestOverridesFromJSONTyped,
    PostPaymentIntentRequestOverridesToJSON,
    PostPaymentIntentRequestOverridesToJSONTyped,
} from './PostPaymentIntentRequestOverrides';

/**
 * 
 * @export
 * @interface PostPaymentIntentRequest
 */
export interface PostPaymentIntentRequest {
    /**
     * 
     * @type {number}
     * @memberof PostPaymentIntentRequest
     */
    providerId: number;
    /**
     * 
     * @type {number}
     * @memberof PostPaymentIntentRequest
     */
    bookingId?: number;
    /**
     * 
     * @type {number}
     * @memberof PostPaymentIntentRequest
     */
    subscriptionId?: number;
    /**
     * 
     * @type {string}
     * @memberof PostPaymentIntentRequest
     */
    customer?: string;
    /**
     * 
     * @type {string}
     * @memberof PostPaymentIntentRequest
     */
    paymentMethod: string;
    /**
     * 
     * @type {number}
     * @memberof PostPaymentIntentRequest
     */
    amount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PostPaymentIntentRequest
     */
    forceAbsorb?: boolean;
    /**
     * 
     * @type {PostPaymentIntentRequestOverrides}
     * @memberof PostPaymentIntentRequest
     */
    overrides?: PostPaymentIntentRequestOverrides;
}

/**
 * Check if a given object implements the PostPaymentIntentRequest interface.
 */
export function instanceOfPostPaymentIntentRequest(value: object): value is PostPaymentIntentRequest {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function PostPaymentIntentRequestFromJSON(json: any): PostPaymentIntentRequest {
    return PostPaymentIntentRequestFromJSONTyped(json, false);
}

export function PostPaymentIntentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPaymentIntentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['provider_id'],
        'bookingId': json['booking_id'] == null ? undefined : json['booking_id'],
        'subscriptionId': json['subscription_id'] == null ? undefined : json['subscription_id'],
        'customer': json['customer'] == null ? undefined : json['customer'],
        'paymentMethod': json['payment_method'],
        'amount': json['amount'],
        'forceAbsorb': json['force_absorb'] == null ? undefined : json['force_absorb'],
        'overrides': json['overrides'] == null ? undefined : PostPaymentIntentRequestOverridesFromJSON(json['overrides']),
    };
}

export function PostPaymentIntentRequestToJSON(json: any): PostPaymentIntentRequest {
    return PostPaymentIntentRequestToJSONTyped(json, false);
}

export function PostPaymentIntentRequestToJSONTyped(value?: PostPaymentIntentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_id': value['providerId'],
        'booking_id': value['bookingId'],
        'subscription_id': value['subscriptionId'],
        'customer': value['customer'],
        'payment_method': value['paymentMethod'],
        'amount': value['amount'],
        'force_absorb': value['forceAbsorb'],
        'overrides': PostPaymentIntentRequestOverridesToJSON(value['overrides']),
    };
}

