/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostStudentRequest
 */
export interface PostStudentRequest {
    /**
     * 
     * @type {number}
     * @memberof PostStudentRequest
     */
    providerId?: number;
    /**
     * 
     * @type {string}
     * @memberof PostStudentRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof PostStudentRequest
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof PostStudentRequest
     */
    dob?: Date;
    /**
     * 
     * @type {string}
     * @memberof PostStudentRequest
     */
    medical?: string;
    /**
     * 
     * @type {string}
     * @memberof PostStudentRequest
     */
    relation?: string;
    /**
     * 
     * @type {number}
     * @memberof PostStudentRequest
     */
    stageId?: number;
    /**
     * 
     * @type {string}
     * @memberof PostStudentRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the PostStudentRequest interface.
 */
export function instanceOfPostStudentRequest(value: object): value is PostStudentRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function PostStudentRequestFromJSON(json: any): PostStudentRequest {
    return PostStudentRequestFromJSONTyped(json, false);
}

export function PostStudentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostStudentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['provider_id'] == null ? undefined : json['provider_id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'dob': json['dob'] == null ? undefined : (new Date(json['dob'])),
        'medical': json['medical'] == null ? undefined : json['medical'],
        'relation': json['relation'] == null ? undefined : json['relation'],
        'stageId': json['stage_id'] == null ? undefined : json['stage_id'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function PostStudentRequestToJSON(json: any): PostStudentRequest {
    return PostStudentRequestToJSONTyped(json, false);
}

export function PostStudentRequestToJSONTyped(value?: PostStudentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_id': value['providerId'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'dob': value['dob'] == null ? undefined : ((value['dob']).toISOString().substring(0,10)),
        'medical': value['medical'],
        'relation': value['relation'],
        'stage_id': value['stageId'],
        'notes': value['notes'],
    };
}

