/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTokenRequest
 */
export interface PostTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof PostTokenRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PostTokenRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof PostTokenRequest
     */
    deviceName: string;
}

/**
 * Check if a given object implements the PostTokenRequest interface.
 */
export function instanceOfPostTokenRequest(value: object): value is PostTokenRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('deviceName' in value) || value['deviceName'] === undefined) return false;
    return true;
}

export function PostTokenRequestFromJSON(json: any): PostTokenRequest {
    return PostTokenRequestFromJSONTyped(json, false);
}

export function PostTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'deviceName': json['device_name'],
    };
}

export function PostTokenRequestToJSON(json: any): PostTokenRequest {
    return PostTokenRequestToJSONTyped(json, false);
}

export function PostTokenRequestToJSONTyped(value?: PostTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'device_name': value['deviceName'],
    };
}

