/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostBookingRequestEmergency
 */
export interface PostBookingRequestEmergency {
    /**
     * 
     * @type {string}
     * @memberof PostBookingRequestEmergency
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PostBookingRequestEmergency
     */
    telephone?: string;
}

/**
 * Check if a given object implements the PostBookingRequestEmergency interface.
 */
export function instanceOfPostBookingRequestEmergency(value: object): value is PostBookingRequestEmergency {
    return true;
}

export function PostBookingRequestEmergencyFromJSON(json: any): PostBookingRequestEmergency {
    return PostBookingRequestEmergencyFromJSONTyped(json, false);
}

export function PostBookingRequestEmergencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostBookingRequestEmergency {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
    };
}

export function PostBookingRequestEmergencyToJSON(json: any): PostBookingRequestEmergency {
    return PostBookingRequestEmergencyToJSONTyped(json, false);
}

export function PostBookingRequestEmergencyToJSONTyped(value?: PostBookingRequestEmergency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'telephone': value['telephone'],
    };
}

