/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Discount } from './Discount';
import {
    instanceOfDiscount,
    DiscountFromJSON,
    DiscountFromJSONTyped,
    DiscountToJSON,
} from './Discount';
import type { Voucher } from './Voucher';
import {
    instanceOfVoucher,
    VoucherFromJSON,
    VoucherFromJSONTyped,
    VoucherToJSON,
} from './Voucher';

/**
 * @type PostApplyCoupon200ResponseData
 * 
 * @export
 */
export type PostApplyCoupon200ResponseData = Discount | Voucher;

export function PostApplyCoupon200ResponseDataFromJSON(json: any): PostApplyCoupon200ResponseData {
    return PostApplyCoupon200ResponseDataFromJSONTyped(json, false);
}

export function PostApplyCoupon200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApplyCoupon200ResponseData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDiscount(json)) {
        return DiscountFromJSONTyped(json, true);
    }
    if (instanceOfVoucher(json)) {
        return VoucherFromJSONTyped(json, true);
    }
    return {} as any;
}

export function PostApplyCoupon200ResponseDataToJSON(json: any): any {
    return PostApplyCoupon200ResponseDataToJSONTyped(json, false);
}

export function PostApplyCoupon200ResponseDataToJSONTyped(value?: PostApplyCoupon200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDiscount(value)) {
        return DiscountToJSON(value as Discount);
    }
    if (instanceOfVoucher(value)) {
        return VoucherToJSON(value as Voucher);
    }
    return {};
}

