/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostStudentStage200ResponseStage
 */
export interface PostStudentStage200ResponseStage {
    /**
     * 
     * @type {number}
     * @memberof PostStudentStage200ResponseStage
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PostStudentStage200ResponseStage
     */
    providerId?: number;
    /**
     * 
     * @type {string}
     * @memberof PostStudentStage200ResponseStage
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PostStudentStage200ResponseStage
     */
    classImage?: string;
    /**
     * 
     * @type {number}
     * @memberof PostStudentStage200ResponseStage
     */
    order?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PostStudentStage200ResponseStage
     */
    _public?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PostStudentStage200ResponseStage
     */
    archivedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PostStudentStage200ResponseStage
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PostStudentStage200ResponseStage
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the PostStudentStage200ResponseStage interface.
 */
export function instanceOfPostStudentStage200ResponseStage(value: object): value is PostStudentStage200ResponseStage {
    return true;
}

export function PostStudentStage200ResponseStageFromJSON(json: any): PostStudentStage200ResponseStage {
    return PostStudentStage200ResponseStageFromJSONTyped(json, false);
}

export function PostStudentStage200ResponseStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostStudentStage200ResponseStage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'providerId': json['provider_id'] == null ? undefined : json['provider_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'classImage': json['class_image'] == null ? undefined : json['class_image'],
        'order': json['order'] == null ? undefined : json['order'],
        '_public': json['public'] == null ? undefined : json['public'],
        'archivedAt': json['archived_at'] == null ? undefined : json['archived_at'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function PostStudentStage200ResponseStageToJSON(json: any): PostStudentStage200ResponseStage {
    return PostStudentStage200ResponseStageToJSONTyped(json, false);
}

export function PostStudentStage200ResponseStageToJSONTyped(value?: PostStudentStage200ResponseStage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'provider_id': value['providerId'],
        'name': value['name'],
        'class_image': value['classImage'],
        'order': value['order'],
        'public': value['_public'],
        'archived_at': value['archivedAt'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

