/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSetupIntentRequestOverrides
 */
export interface PostSetupIntentRequestOverrides {
    /**
     * 
     * @type {Array<string>}
     * @memberof PostSetupIntentRequestOverrides
     */
    paymentMethodTypes?: Array<string>;
}

/**
 * Check if a given object implements the PostSetupIntentRequestOverrides interface.
 */
export function instanceOfPostSetupIntentRequestOverrides(value: object): value is PostSetupIntentRequestOverrides {
    return true;
}

export function PostSetupIntentRequestOverridesFromJSON(json: any): PostSetupIntentRequestOverrides {
    return PostSetupIntentRequestOverridesFromJSONTyped(json, false);
}

export function PostSetupIntentRequestOverridesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSetupIntentRequestOverrides {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentMethodTypes': json['payment_method_types'] == null ? undefined : json['payment_method_types'],
    };
}

export function PostSetupIntentRequestOverridesToJSON(json: any): PostSetupIntentRequestOverrides {
    return PostSetupIntentRequestOverridesToJSONTyped(json, false);
}

export function PostSetupIntentRequestOverridesToJSONTyped(value?: PostSetupIntentRequestOverrides | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_method_types': value['paymentMethodTypes'],
    };
}

