/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostConnectAcceptRequest
 */
export interface PostConnectAcceptRequest {
    /**
     * 
     * @type {boolean}
     * @memberof PostConnectAcceptRequest
     */
    terms?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostConnectAcceptRequest
     */
    marketing?: boolean;
}

/**
 * Check if a given object implements the PostConnectAcceptRequest interface.
 */
export function instanceOfPostConnectAcceptRequest(value: object): value is PostConnectAcceptRequest {
    return true;
}

export function PostConnectAcceptRequestFromJSON(json: any): PostConnectAcceptRequest {
    return PostConnectAcceptRequestFromJSONTyped(json, false);
}

export function PostConnectAcceptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostConnectAcceptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'terms': json['terms'] == null ? undefined : json['terms'],
        'marketing': json['marketing'] == null ? undefined : json['marketing'],
    };
}

export function PostConnectAcceptRequestToJSON(json: any): PostConnectAcceptRequest {
    return PostConnectAcceptRequestToJSONTyped(json, false);
}

export function PostConnectAcceptRequestToJSONTyped(value?: PostConnectAcceptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'terms': value['terms'],
        'marketing': value['marketing'],
    };
}

