/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPaymentIntentRequestOverrides
 */
export interface PostPaymentIntentRequestOverrides {
    /**
     * 
     * @type {Array<string>}
     * @memberof PostPaymentIntentRequestOverrides
     */
    paymentMethodTypes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PostPaymentIntentRequestOverrides
     */
    setupFutureUsage?: string;
    /**
     * 
     * @type {string}
     * @memberof PostPaymentIntentRequestOverrides
     */
    captureMethod?: string;
}

/**
 * Check if a given object implements the PostPaymentIntentRequestOverrides interface.
 */
export function instanceOfPostPaymentIntentRequestOverrides(value: object): value is PostPaymentIntentRequestOverrides {
    return true;
}

export function PostPaymentIntentRequestOverridesFromJSON(json: any): PostPaymentIntentRequestOverrides {
    return PostPaymentIntentRequestOverridesFromJSONTyped(json, false);
}

export function PostPaymentIntentRequestOverridesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPaymentIntentRequestOverrides {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentMethodTypes': json['payment_method_types'] == null ? undefined : json['payment_method_types'],
        'setupFutureUsage': json['setup_future_usage'] == null ? undefined : json['setup_future_usage'],
        'captureMethod': json['capture_method'] == null ? undefined : json['capture_method'],
    };
}

export function PostPaymentIntentRequestOverridesToJSON(json: any): PostPaymentIntentRequestOverrides {
    return PostPaymentIntentRequestOverridesToJSONTyped(json, false);
}

export function PostPaymentIntentRequestOverridesToJSONTyped(value?: PostPaymentIntentRequestOverrides | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_method_types': value['paymentMethodTypes'],
        'setup_future_usage': value['setupFutureUsage'],
        'capture_method': value['captureMethod'],
    };
}

