/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostStudentGoal200Response
 */
export interface PostStudentGoal200Response {
    /**
     * 
     * @type {number}
     * @memberof PostStudentGoal200Response
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PostStudentGoal200Response
     */
    goalId?: number;
    /**
     * 
     * @type {number}
     * @memberof PostStudentGoal200Response
     */
    studentId?: number;
    /**
     * 
     * @type {number}
     * @memberof PostStudentGoal200Response
     */
    bookingId?: number;
    /**
     * 
     * @type {string}
     * @memberof PostStudentGoal200Response
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PostStudentGoal200Response
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the PostStudentGoal200Response interface.
 */
export function instanceOfPostStudentGoal200Response(value: object): value is PostStudentGoal200Response {
    return true;
}

export function PostStudentGoal200ResponseFromJSON(json: any): PostStudentGoal200Response {
    return PostStudentGoal200ResponseFromJSONTyped(json, false);
}

export function PostStudentGoal200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostStudentGoal200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'goalId': json['goal_id'] == null ? undefined : json['goal_id'],
        'studentId': json['student_id'] == null ? undefined : json['student_id'],
        'bookingId': json['booking_id'] == null ? undefined : json['booking_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function PostStudentGoal200ResponseToJSON(json: any): PostStudentGoal200Response {
    return PostStudentGoal200ResponseToJSONTyped(json, false);
}

export function PostStudentGoal200ResponseToJSONTyped(value?: PostStudentGoal200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'goal_id': value['goalId'],
        'student_id': value['studentId'],
        'booking_id': value['bookingId'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

