/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostSetupIntentRequestOverrides } from './PostSetupIntentRequestOverrides';
import {
    PostSetupIntentRequestOverridesFromJSON,
    PostSetupIntentRequestOverridesFromJSONTyped,
    PostSetupIntentRequestOverridesToJSON,
    PostSetupIntentRequestOverridesToJSONTyped,
} from './PostSetupIntentRequestOverrides';

/**
 * 
 * @export
 * @interface PostSetupIntentRequest
 */
export interface PostSetupIntentRequest {
    /**
     * 
     * @type {number}
     * @memberof PostSetupIntentRequest
     */
    providerId: number;
    /**
     * 
     * @type {string}
     * @memberof PostSetupIntentRequest
     */
    customer: string;
    /**
     * 
     * @type {PostSetupIntentRequestOverrides}
     * @memberof PostSetupIntentRequest
     */
    overrides?: PostSetupIntentRequestOverrides;
}

/**
 * Check if a given object implements the PostSetupIntentRequest interface.
 */
export function instanceOfPostSetupIntentRequest(value: object): value is PostSetupIntentRequest {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('customer' in value) || value['customer'] === undefined) return false;
    return true;
}

export function PostSetupIntentRequestFromJSON(json: any): PostSetupIntentRequest {
    return PostSetupIntentRequestFromJSONTyped(json, false);
}

export function PostSetupIntentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSetupIntentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['provider_id'],
        'customer': json['customer'],
        'overrides': json['overrides'] == null ? undefined : PostSetupIntentRequestOverridesFromJSON(json['overrides']),
    };
}

export function PostSetupIntentRequestToJSON(json: any): PostSetupIntentRequest {
    return PostSetupIntentRequestToJSONTyped(json, false);
}

export function PostSetupIntentRequestToJSONTyped(value?: PostSetupIntentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_id': value['providerId'],
        'customer': value['customer'],
        'overrides': PostSetupIntentRequestOverridesToJSON(value['overrides']),
    };
}

