/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostWaiteeRequestStudentsInner } from './PostWaiteeRequestStudentsInner';
import {
    PostWaiteeRequestStudentsInnerFromJSON,
    PostWaiteeRequestStudentsInnerFromJSONTyped,
    PostWaiteeRequestStudentsInnerToJSON,
    PostWaiteeRequestStudentsInnerToJSONTyped,
} from './PostWaiteeRequestStudentsInner';
import type { PostWaiteeRequestDaysInner } from './PostWaiteeRequestDaysInner';
import {
    PostWaiteeRequestDaysInnerFromJSON,
    PostWaiteeRequestDaysInnerFromJSONTyped,
    PostWaiteeRequestDaysInnerToJSON,
    PostWaiteeRequestDaysInnerToJSONTyped,
} from './PostWaiteeRequestDaysInner';

/**
 * 
 * @export
 * @interface PostWaiteeRequest
 */
export interface PostWaiteeRequest {
    /**
     * 
     * @type {number}
     * @memberof PostWaiteeRequest
     */
    providerId: number;
    /**
     * 
     * @type {string}
     * @memberof PostWaiteeRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PostWaiteeRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PostWaiteeRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PostWaiteeRequest
     */
    telephone?: string;
    /**
     * 
     * @type {Array<PostWaiteeRequestStudentsInner>}
     * @memberof PostWaiteeRequest
     */
    students: Array<PostWaiteeRequestStudentsInner>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PostWaiteeRequest
     */
    venues: Array<number>;
    /**
     * 
     * @type {Array<PostWaiteeRequestDaysInner>}
     * @memberof PostWaiteeRequest
     */
    days: Array<PostWaiteeRequestDaysInner>;
    /**
     * 
     * @type {string}
     * @memberof PostWaiteeRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the PostWaiteeRequest interface.
 */
export function instanceOfPostWaiteeRequest(value: object): value is PostWaiteeRequest {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('students' in value) || value['students'] === undefined) return false;
    if (!('venues' in value) || value['venues'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    return true;
}

export function PostWaiteeRequestFromJSON(json: any): PostWaiteeRequest {
    return PostWaiteeRequestFromJSONTyped(json, false);
}

export function PostWaiteeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWaiteeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['provider_id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'students': ((json['students'] as Array<any>).map(PostWaiteeRequestStudentsInnerFromJSON)),
        'venues': json['venues'],
        'days': ((json['days'] as Array<any>).map(PostWaiteeRequestDaysInnerFromJSON)),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function PostWaiteeRequestToJSON(json: any): PostWaiteeRequest {
    return PostWaiteeRequestToJSONTyped(json, false);
}

export function PostWaiteeRequestToJSONTyped(value?: PostWaiteeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_id': value['providerId'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'telephone': value['telephone'],
        'students': ((value['students'] as Array<any>).map(PostWaiteeRequestStudentsInnerToJSON)),
        'venues': value['venues'],
        'days': ((value['days'] as Array<any>).map(PostWaiteeRequestDaysInnerToJSON)),
        'notes': value['notes'],
    };
}

