/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Plan } from './Plan';
import {
    PlanFromJSON,
    PlanFromJSONTyped,
    PlanToJSON,
    PlanToJSONTyped,
} from './Plan';

/**
 * 
 * @export
 * @interface Price
 */
export interface Price {
    /**
     * 
     * @type {number}
     * @memberof Price
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Price
     */
    type: PriceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Price
     */
    paymentMethod: PricePaymentMethodEnum;
    /**
     * 
     * @type {number}
     * @memberof Price
     */
    fixedCost?: number;
    /**
     * 
     * @type {number}
     * @memberof Price
     */
    sessionLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof Price
     */
    sessionSelectionType?: PriceSessionSelectionTypeEnum;
    /**
     * 
     * @type {Plan}
     * @memberof Price
     */
    plan?: Plan;
}


/**
 * @export
 */
export const PriceTypeEnum = {
    PerSession: 'perSession',
    PerTrial: 'perTrial',
    FixedCost: 'fixedCost'
} as const;
export type PriceTypeEnum = typeof PriceTypeEnum[keyof typeof PriceTypeEnum];

/**
 * @export
 */
export const PricePaymentMethodEnum = {
    Card: 'card',
    Subscription: 'subscription',
    Bank: 'bank',
    Bacs: 'bacs'
} as const;
export type PricePaymentMethodEnum = typeof PricePaymentMethodEnum[keyof typeof PricePaymentMethodEnum];

/**
 * @export
 */
export const PriceSessionSelectionTypeEnum = {
    FixedStart: 'fixedStart',
    FlexiStart: 'flexiStart',
    CherryPick: 'cherryPick'
} as const;
export type PriceSessionSelectionTypeEnum = typeof PriceSessionSelectionTypeEnum[keyof typeof PriceSessionSelectionTypeEnum];


/**
 * Check if a given object implements the Price interface.
 */
export function instanceOfPrice(value: object): value is Price {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function PriceFromJSON(json: any): Price {
    return PriceFromJSONTyped(json, false);
}

export function PriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Price {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'paymentMethod': json['payment_method'],
        'fixedCost': json['fixed_cost'] == null ? undefined : json['fixed_cost'],
        'sessionLimit': json['session_limit'] == null ? undefined : json['session_limit'],
        'sessionSelectionType': json['session_selection_type'] == null ? undefined : json['session_selection_type'],
        'plan': json['plan'] == null ? undefined : PlanFromJSON(json['plan']),
    };
}

export function PriceToJSON(json: any): Price {
    return PriceToJSONTyped(json, false);
}

export function PriceToJSONTyped(value?: Price | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'payment_method': value['paymentMethod'],
        'fixed_cost': value['fixedCost'],
        'session_limit': value['sessionLimit'],
        'session_selection_type': value['sessionSelectionType'],
        'plan': PlanToJSON(value['plan']),
    };
}

