/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProgressMode = {
    Basic: 'basic',
    Idm: 'idm'
} as const;
export type ProgressMode = typeof ProgressMode[keyof typeof ProgressMode];


export function instanceOfProgressMode(value: any): boolean {
    for (const key in ProgressMode) {
        if (Object.prototype.hasOwnProperty.call(ProgressMode, key)) {
            if (ProgressMode[key as keyof typeof ProgressMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProgressModeFromJSON(json: any): ProgressMode {
    return ProgressModeFromJSONTyped(json, false);
}

export function ProgressModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgressMode {
    return json as ProgressMode;
}

export function ProgressModeToJSON(value?: ProgressMode | null): any {
    return value as any;
}

export function ProgressModeToJSONTyped(value: any, ignoreDiscriminator: boolean): ProgressMode {
    return value as ProgressMode;
}

