/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Type } from './Type';
import {
    TypeFromJSON,
    TypeFromJSONTyped,
    TypeToJSON,
    TypeToJSONTyped,
} from './Type';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';
import type { Venue } from './Venue';
import {
    VenueFromJSON,
    VenueFromJSONTyped,
    VenueToJSON,
    VenueToJSONTyped,
} from './Venue';
import type { ProviderBookingSettings } from './ProviderBookingSettings';
import {
    ProviderBookingSettingsFromJSON,
    ProviderBookingSettingsFromJSONTyped,
    ProviderBookingSettingsToJSON,
    ProviderBookingSettingsToJSONTyped,
} from './ProviderBookingSettings';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';
import type { ProviderCatchUpSettings } from './ProviderCatchUpSettings';
import {
    ProviderCatchUpSettingsFromJSON,
    ProviderCatchUpSettingsFromJSONTyped,
    ProviderCatchUpSettingsToJSON,
    ProviderCatchUpSettingsToJSONTyped,
} from './ProviderCatchUpSettings';
import type { Stage } from './Stage';
import {
    StageFromJSON,
    StageFromJSONTyped,
    StageToJSON,
    StageToJSONTyped,
} from './Stage';
import type { Facility } from './Facility';
import {
    FacilityFromJSON,
    FacilityFromJSONTyped,
    FacilityToJSON,
    FacilityToJSONTyped,
} from './Facility';
import type { ProviderNotificationSettings } from './ProviderNotificationSettings';
import {
    ProviderNotificationSettingsFromJSON,
    ProviderNotificationSettingsFromJSONTyped,
    ProviderNotificationSettingsToJSON,
    ProviderNotificationSettingsToJSONTyped,
} from './ProviderNotificationSettings';
import type { Term } from './Term';
import {
    TermFromJSON,
    TermFromJSONTyped,
    TermToJSON,
    TermToJSONTyped,
} from './Term';
import type { ProviderWaitingListSettings } from './ProviderWaitingListSettings';
import {
    ProviderWaitingListSettingsFromJSON,
    ProviderWaitingListSettingsFromJSONTyped,
    ProviderWaitingListSettingsToJSON,
    ProviderWaitingListSettingsToJSONTyped,
} from './ProviderWaitingListSettings';

/**
 * 
 * @export
 * @interface ProviderWithType
 */
export interface ProviderWithType {
    /**
     * 
     * @type {number}
     * @memberof ProviderWithType
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    classImage?: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    strapline?: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    handle: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    telephone?: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    stripeId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderWithType
     */
    absorbFee: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderWithType
     */
    verified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderWithType
     */
    featured?: boolean;
    /**
     * 
     * @type {ProviderBookingSettings}
     * @memberof ProviderWithType
     */
    bookingSettings?: ProviderBookingSettings;
    /**
     * 
     * @type {ProviderCatchUpSettings}
     * @memberof ProviderWithType
     */
    catchUpSettings?: ProviderCatchUpSettings;
    /**
     * 
     * @type {ProviderWaitingListSettings}
     * @memberof ProviderWithType
     */
    waitingListSettings?: ProviderWaitingListSettings;
    /**
     * 
     * @type {ProviderNotificationSettings}
     * @memberof ProviderWithType
     */
    notificationSettings?: ProviderNotificationSettings;
    /**
     * 
     * @type {Array<Category>}
     * @memberof ProviderWithType
     */
    categories?: Array<Category>;
    /**
     * 
     * @type {Array<Type>}
     * @memberof ProviderWithType
     */
    types?: Array<Type>;
    /**
     * 
     * @type {Array<Facility>}
     * @memberof ProviderWithType
     */
    facilities?: Array<Facility>;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    termsAndConditions?: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    privacyPolicy?: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    photoConsent?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProviderWithType
     */
    connectedAt?: Date;
    /**
     * 
     * @type {Array<Term>}
     * @memberof ProviderWithType
     */
    terms?: Array<Term>;
    /**
     * 
     * @type {Array<Venue>}
     * @memberof ProviderWithType
     */
    venues?: Array<Venue>;
    /**
     * 
     * @type {Array<Stage>}
     * @memberof ProviderWithType
     */
    stages?: Array<Stage>;
    /**
     * 
     * @type {Array<Product>}
     * @memberof ProviderWithType
     */
    vouchers?: Array<Product>;
    /**
     * 
     * @type {string}
     * @memberof ProviderWithType
     */
    type: ProviderWithTypeTypeEnum;
}


/**
 * @export
 */
export const ProviderWithTypeTypeEnum = {
    Provider: 'provider'
} as const;
export type ProviderWithTypeTypeEnum = typeof ProviderWithTypeTypeEnum[keyof typeof ProviderWithTypeTypeEnum];


/**
 * Check if a given object implements the ProviderWithType interface.
 */
export function instanceOfProviderWithType(value: object): value is ProviderWithType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('handle' in value) || value['handle'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('absorbFee' in value) || value['absorbFee'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ProviderWithTypeFromJSON(json: any): ProviderWithType {
    return ProviderWithTypeFromJSONTyped(json, false);
}

export function ProviderWithTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderWithType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'classImage': json['class_image'] == null ? undefined : json['class_image'],
        'strapline': json['strapline'] == null ? undefined : json['strapline'],
        'description': json['description'] == null ? undefined : json['description'],
        'handle': json['handle'],
        'email': json['email'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'website': json['website'] == null ? undefined : json['website'],
        'stripeId': json['stripe_id'] == null ? undefined : json['stripe_id'],
        'absorbFee': json['absorb_fee'],
        'verified': json['verified'] == null ? undefined : json['verified'],
        'featured': json['featured'] == null ? undefined : json['featured'],
        'bookingSettings': json['booking_settings'] == null ? undefined : ProviderBookingSettingsFromJSON(json['booking_settings']),
        'catchUpSettings': json['catch_up_settings'] == null ? undefined : ProviderCatchUpSettingsFromJSON(json['catch_up_settings']),
        'waitingListSettings': json['waiting_list_settings'] == null ? undefined : ProviderWaitingListSettingsFromJSON(json['waiting_list_settings']),
        'notificationSettings': json['notification_settings'] == null ? undefined : ProviderNotificationSettingsFromJSON(json['notification_settings']),
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(CategoryFromJSON)),
        'types': json['types'] == null ? undefined : ((json['types'] as Array<any>).map(TypeFromJSON)),
        'facilities': json['facilities'] == null ? undefined : ((json['facilities'] as Array<any>).map(FacilityFromJSON)),
        'termsAndConditions': json['terms_and_conditions'] == null ? undefined : json['terms_and_conditions'],
        'privacyPolicy': json['privacy_policy'] == null ? undefined : json['privacy_policy'],
        'photoConsent': json['photo_consent'] == null ? undefined : json['photo_consent'],
        'connectedAt': json['connected_at'] == null ? undefined : (new Date(json['connected_at'])),
        'terms': json['terms'] == null ? undefined : ((json['terms'] as Array<any>).map(TermFromJSON)),
        'venues': json['venues'] == null ? undefined : ((json['venues'] as Array<any>).map(VenueFromJSON)),
        'stages': json['stages'] == null ? undefined : ((json['stages'] as Array<any>).map(StageFromJSON)),
        'vouchers': json['vouchers'] == null ? undefined : ((json['vouchers'] as Array<any>).map(ProductFromJSON)),
        'type': json['type'],
    };
}

export function ProviderWithTypeToJSON(json: any): ProviderWithType {
    return ProviderWithTypeToJSONTyped(json, false);
}

export function ProviderWithTypeToJSONTyped(value?: ProviderWithType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'icon': value['icon'],
        'class_image': value['classImage'],
        'strapline': value['strapline'],
        'description': value['description'],
        'handle': value['handle'],
        'email': value['email'],
        'telephone': value['telephone'],
        'website': value['website'],
        'stripe_id': value['stripeId'],
        'absorb_fee': value['absorbFee'],
        'verified': value['verified'],
        'featured': value['featured'],
        'booking_settings': ProviderBookingSettingsToJSON(value['bookingSettings']),
        'catch_up_settings': ProviderCatchUpSettingsToJSON(value['catchUpSettings']),
        'waiting_list_settings': ProviderWaitingListSettingsToJSON(value['waitingListSettings']),
        'notification_settings': ProviderNotificationSettingsToJSON(value['notificationSettings']),
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(CategoryToJSON)),
        'types': value['types'] == null ? undefined : ((value['types'] as Array<any>).map(TypeToJSON)),
        'facilities': value['facilities'] == null ? undefined : ((value['facilities'] as Array<any>).map(FacilityToJSON)),
        'terms_and_conditions': value['termsAndConditions'],
        'privacy_policy': value['privacyPolicy'],
        'photo_consent': value['photoConsent'],
        'connected_at': value['connectedAt'] == null ? undefined : ((value['connectedAt']).toISOString()),
        'terms': value['terms'] == null ? undefined : ((value['terms'] as Array<any>).map(TermToJSON)),
        'venues': value['venues'] == null ? undefined : ((value['venues'] as Array<any>).map(VenueToJSON)),
        'stages': value['stages'] == null ? undefined : ((value['stages'] as Array<any>).map(StageToJSON)),
        'vouchers': value['vouchers'] == null ? undefined : ((value['vouchers'] as Array<any>).map(ProductToJSON)),
        'type': value['type'],
    };
}

