/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderBookingSettings
 */
export interface ProviderBookingSettings {
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    dob?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    notes?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    medical?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    space?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    referral?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    stage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    ageRange?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    sameDay?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    locoParentis?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderBookingSettings
     */
    advertiseFull?: boolean;
}

/**
 * Check if a given object implements the ProviderBookingSettings interface.
 */
export function instanceOfProviderBookingSettings(value: object): value is ProviderBookingSettings {
    return true;
}

export function ProviderBookingSettingsFromJSON(json: any): ProviderBookingSettings {
    return ProviderBookingSettingsFromJSONTyped(json, false);
}

export function ProviderBookingSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderBookingSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'dob': json['dob'] == null ? undefined : json['dob'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'medical': json['medical'] == null ? undefined : json['medical'],
        'space': json['space'] == null ? undefined : json['space'],
        'referral': json['referral'] == null ? undefined : json['referral'],
        'stage': json['stage'] == null ? undefined : json['stage'],
        'ageRange': json['age_range'] == null ? undefined : json['age_range'],
        'sameDay': json['same_day'] == null ? undefined : json['same_day'],
        'locoParentis': json['loco_parentis'] == null ? undefined : json['loco_parentis'],
        'advertiseFull': json['advertise_full'] == null ? undefined : json['advertise_full'],
    };
}

export function ProviderBookingSettingsToJSON(json: any): ProviderBookingSettings {
    return ProviderBookingSettingsToJSONTyped(json, false);
}

export function ProviderBookingSettingsToJSONTyped(value?: ProviderBookingSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dob': value['dob'],
        'notes': value['notes'],
        'medical': value['medical'],
        'space': value['space'],
        'referral': value['referral'],
        'stage': value['stage'],
        'age_range': value['ageRange'],
        'same_day': value['sameDay'],
        'loco_parentis': value['locoParentis'],
        'advertise_full': value['advertiseFull'],
    };
}

