/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PhotoConsentContent } from './PhotoConsentContent';
import {
    instanceOfPhotoConsentContent,
    PhotoConsentContentFromJSON,
    PhotoConsentContentFromJSONTyped,
    PhotoConsentContentToJSON,
} from './PhotoConsentContent';
import type { PhotoConsentLink } from './PhotoConsentLink';
import {
    instanceOfPhotoConsentLink,
    PhotoConsentLinkFromJSON,
    PhotoConsentLinkFromJSONTyped,
    PhotoConsentLinkToJSON,
} from './PhotoConsentLink';

/**
 * @type ProviderPhotoConsent
 * 
 * @export
 */
export type ProviderPhotoConsent = PhotoConsentContent | PhotoConsentLink;

export function ProviderPhotoConsentFromJSON(json: any): ProviderPhotoConsent {
    return ProviderPhotoConsentFromJSONTyped(json, false);
}

export function ProviderPhotoConsentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderPhotoConsent {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPhotoConsentContent(json)) {
        return PhotoConsentContentFromJSONTyped(json, true);
    }
    if (instanceOfPhotoConsentLink(json)) {
        return PhotoConsentLinkFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ProviderPhotoConsentToJSON(json: any): any {
    return ProviderPhotoConsentToJSONTyped(json, false);
}

export function ProviderPhotoConsentToJSONTyped(value?: ProviderPhotoConsent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPhotoConsentContent(value)) {
        return PhotoConsentContentToJSON(value as PhotoConsentContent);
    }
    if (instanceOfPhotoConsentLink(value)) {
        return PhotoConsentLinkToJSON(value as PhotoConsentLink);
    }
    return {};
}

