/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderNotificationSettings
 */
export interface ProviderNotificationSettings {
    /**
     * 
     * @type {boolean}
     * @memberof ProviderNotificationSettings
     */
    sessionReminders?: boolean;
}

/**
 * Check if a given object implements the ProviderNotificationSettings interface.
 */
export function instanceOfProviderNotificationSettings(value: object): value is ProviderNotificationSettings {
    return true;
}

export function ProviderNotificationSettingsFromJSON(json: any): ProviderNotificationSettings {
    return ProviderNotificationSettingsFromJSONTyped(json, false);
}

export function ProviderNotificationSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderNotificationSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionReminders': json['session_reminders'] == null ? undefined : json['session_reminders'],
    };
}

export function ProviderNotificationSettingsToJSON(json: any): ProviderNotificationSettings {
    return ProviderNotificationSettingsToJSONTyped(json, false);
}

export function ProviderNotificationSettingsToJSONTyped(value?: ProviderNotificationSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'session_reminders': value['sessionReminders'],
    };
}

