/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Session
 */
export interface Session {
    /**
     * 
     * @type {number}
     * @memberof Session
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Session
     */
    dateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Session
     */
    movedFrom?: Date;
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    teacherName?: string;
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    venueName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Session
     */
    cancelled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Session
     */
    spacesCount?: number;
}

/**
 * Check if a given object implements the Session interface.
 */
export function instanceOfSession(value: object): value is Session {
    return true;
}

export function SessionFromJSON(json: any): Session {
    return SessionFromJSONTyped(json, false);
}

export function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'dateTime': json['date_time'] == null ? undefined : (new Date(json['date_time'])),
        'movedFrom': json['moved_from'] == null ? undefined : (new Date(json['moved_from'])),
        'teacherName': json['teacher_name'] == null ? undefined : json['teacher_name'],
        'venueName': json['venue_name'] == null ? undefined : json['venue_name'],
        'cancelled': json['cancelled'] == null ? undefined : json['cancelled'],
        'spacesCount': json['spaces_count'] == null ? undefined : json['spaces_count'],
    };
}

export function SessionToJSON(json: any): Session {
    return SessionToJSONTyped(json, false);
}

export function SessionToJSONTyped(value?: Session | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date_time': value['dateTime'] == null ? undefined : ((value['dateTime']).toISOString()),
        'moved_from': value['movedFrom'] == null ? undefined : ((value['movedFrom']).toISOString()),
        'teacher_name': value['teacherName'],
        'venue_name': value['venueName'],
        'cancelled': value['cancelled'],
        'spaces_count': value['spacesCount'],
    };
}

