/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudentGoal } from './StudentGoal';
import {
    StudentGoalFromJSON,
    StudentGoalFromJSONTyped,
    StudentGoalToJSON,
    StudentGoalToJSONTyped,
} from './StudentGoal';

/**
 * 
 * @export
 * @interface StudentStage
 */
export interface StudentStage {
    /**
     * 
     * @type {number}
     * @memberof StudentStage
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof StudentStage
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof StudentStage
     */
    providerId: number;
    /**
     * 
     * @type {string}
     * @memberof StudentStage
     */
    providerName: string;
    /**
     * 
     * @type {boolean}
     * @memberof StudentStage
     */
    active: boolean;
    /**
     * 
     * @type {Date}
     * @memberof StudentStage
     */
    awardedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof StudentStage
     */
    badgeImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentStage
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentStage
     */
    certificateUrl?: string;
    /**
     * 
     * @type {Array<StudentGoal>}
     * @memberof StudentStage
     */
    goals: Array<StudentGoal>;
}

/**
 * Check if a given object implements the StudentStage interface.
 */
export function instanceOfStudentStage(value: object): value is StudentStage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('providerName' in value) || value['providerName'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('goals' in value) || value['goals'] === undefined) return false;
    return true;
}

export function StudentStageFromJSON(json: any): StudentStage {
    return StudentStageFromJSONTyped(json, false);
}

export function StudentStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentStage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'providerId': json['provider_id'],
        'providerName': json['provider_name'],
        'active': json['active'],
        'awardedOn': json['awarded_on'] == null ? undefined : (new Date(json['awarded_on'])),
        'badgeImageUrl': json['badge_image_url'] == null ? undefined : json['badge_image_url'],
        'description': json['description'] == null ? undefined : json['description'],
        'certificateUrl': json['certificate_url'] == null ? undefined : json['certificate_url'],
        'goals': ((json['goals'] as Array<any>).map(StudentGoalFromJSON)),
    };
}

export function StudentStageToJSON(json: any): StudentStage {
    return StudentStageToJSONTyped(json, false);
}

export function StudentStageToJSONTyped(value?: StudentStage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'provider_id': value['providerId'],
        'provider_name': value['providerName'],
        'active': value['active'],
        'awarded_on': value['awardedOn'] == null ? undefined : ((value['awardedOn']).toISOString().substring(0,10)),
        'badge_image_url': value['badgeImageUrl'],
        'description': value['description'],
        'certificate_url': value['certificateUrl'],
        'goals': ((value['goals'] as Array<any>).map(StudentGoalToJSON)),
    };
}

