/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentGoal
 */
export interface StudentGoal {
    /**
     * 
     * @type {number}
     * @memberof StudentGoal
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof StudentGoal
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof StudentGoal
     */
    achievedAt?: Date;
}

/**
 * Check if a given object implements the StudentGoal interface.
 */
export function instanceOfStudentGoal(value: object): value is StudentGoal {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StudentGoalFromJSON(json: any): StudentGoal {
    return StudentGoalFromJSONTyped(json, false);
}

export function StudentGoalFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentGoal {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'achievedAt': json['achieved_at'] == null ? undefined : (new Date(json['achieved_at'])),
    };
}

export function StudentGoalToJSON(json: any): StudentGoal {
    return StudentGoalToJSONTyped(json, false);
}

export function StudentGoalToJSONTyped(value?: StudentGoal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'achieved_at': value['achievedAt'] == null ? undefined : ((value['achievedAt']).toISOString()),
    };
}

