/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Student
 */
export interface Student {
    /**
     * 
     * @type {number}
     * @memberof Student
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Student
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof Student
     */
    lastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof Student
     */
    dob?: Date;
    /**
     * 
     * @type {string}
     * @memberof Student
     */
    medical?: string;
    /**
     * 
     * @type {string}
     * @memberof Student
     */
    relation?: string;
}

/**
 * Check if a given object implements the Student interface.
 */
export function instanceOfStudent(value: object): value is Student {
    return true;
}

export function StudentFromJSON(json: any): Student {
    return StudentFromJSONTyped(json, false);
}

export function StudentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Student {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'dob': json['dob'] == null ? undefined : (new Date(json['dob'])),
        'medical': json['medical'] == null ? undefined : json['medical'],
        'relation': json['relation'] == null ? undefined : json['relation'],
    };
}

export function StudentToJSON(json: any): Student {
    return StudentToJSONTyped(json, false);
}

export function StudentToJSONTyped(value?: Student | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'dob': value['dob'] == null ? undefined : ((value['dob']).toISOString().substring(0,10)),
        'medical': value['medical'],
        'relation': value['relation'],
    };
}

