/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StudentGoalStatus = {
    NotStarted: 'notStarted',
    Introduced: 'introduced',
    Developing: 'developing',
    Mastered: 'mastered'
} as const;
export type StudentGoalStatus = typeof StudentGoalStatus[keyof typeof StudentGoalStatus];


export function instanceOfStudentGoalStatus(value: any): boolean {
    for (const key in StudentGoalStatus) {
        if (Object.prototype.hasOwnProperty.call(StudentGoalStatus, key)) {
            if (StudentGoalStatus[key as keyof typeof StudentGoalStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StudentGoalStatusFromJSON(json: any): StudentGoalStatus {
    return StudentGoalStatusFromJSONTyped(json, false);
}

export function StudentGoalStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentGoalStatus {
    return json as StudentGoalStatus;
}

export function StudentGoalStatusToJSON(value?: StudentGoalStatus | null): any {
    return value as any;
}

export function StudentGoalStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): StudentGoalStatus {
    return value as StudentGoalStatus;
}

