/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    providerId: number;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    planName: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    studentName: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    paymentMethod: string;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    goal: number;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    amount: number;
    /**
     * 
     * @type {boolean}
     * @memberof Subscription
     */
    stripeActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    startsAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    trialEndsAt: Date;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    outstandingPaymentsCount: number;
}

/**
 * Check if a given object implements the Subscription interface.
 */
export function instanceOfSubscription(value: object): value is Subscription {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('planName' in value) || value['planName'] === undefined) return false;
    if (!('studentName' in value) || value['studentName'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('goal' in value) || value['goal'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('stripeActive' in value) || value['stripeActive'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('trialEndsAt' in value) || value['trialEndsAt'] === undefined) return false;
    if (!('outstandingPaymentsCount' in value) || value['outstandingPaymentsCount'] === undefined) return false;
    return true;
}

export function SubscriptionFromJSON(json: any): Subscription {
    return SubscriptionFromJSONTyped(json, false);
}

export function SubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscription {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'providerId': json['provider_id'],
        'planName': json['plan_name'],
        'studentName': json['student_name'],
        'paymentMethod': json['payment_method'],
        'goal': json['goal'],
        'amount': json['amount'],
        'stripeActive': json['stripe_active'],
        'startsAt': (new Date(json['starts_at'])),
        'trialEndsAt': (new Date(json['trial_ends_at'])),
        'outstandingPaymentsCount': json['outstanding_payments_count'],
    };
}

export function SubscriptionToJSON(json: any): Subscription {
    return SubscriptionToJSONTyped(json, false);
}

export function SubscriptionToJSONTyped(value?: Subscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'provider_id': value['providerId'],
        'plan_name': value['planName'],
        'student_name': value['studentName'],
        'payment_method': value['paymentMethod'],
        'goal': value['goal'],
        'amount': value['amount'],
        'stripe_active': value['stripeActive'],
        'starts_at': ((value['startsAt']).toISOString()),
        'trial_ends_at': ((value['trialEndsAt']).toISOString()),
        'outstanding_payments_count': value['outstandingPaymentsCount'],
    };
}

