/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Term
 */
export interface Term {
    /**
     * 
     * @type {number}
     * @memberof Term
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Term
     */
    name?: string;
}

/**
 * Check if a given object implements the Term interface.
 */
export function instanceOfTerm(value: object): value is Term {
    return true;
}

export function TermFromJSON(json: any): Term {
    return TermFromJSONTyped(json, false);
}

export function TermFromJSONTyped(json: any, ignoreDiscriminator: boolean): Term {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function TermToJSON(json: any): Term {
    return TermToJSONTyped(json, false);
}

export function TermToJSONTyped(value?: Term | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

