/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Type = {
    AccessibleInclusivePlaces: 'accessible-inclusive-places',
    BabyToddler: 'baby-toddler',
    CommunityEvents: 'community-events',
    FamilyDaysOut: 'family-days-out',
    HolidayCamps: 'holiday-camps',
    IndoorActivities: 'indoor-activities',
    KidsActivities: 'kids-activities',
    OutdoorActivities: 'outdoor-activities',
    PetFriendlySpac: 'pet-friendly-spac',
    SeasonsTraditions: 'seasons-traditions'
} as const;
export type Type = typeof Type[keyof typeof Type];


export function instanceOfType(value: any): boolean {
    for (const key in Type) {
        if (Object.prototype.hasOwnProperty.call(Type, key)) {
            if (Type[key as keyof typeof Type] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TypeFromJSON(json: any): Type {
    return TypeFromJSONTyped(json, false);
}

export function TypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Type {
    return json as Type;
}

export function TypeToJSON(value?: Type | null): any {
    return value as any;
}

export function TypeToJSONTyped(value: any, ignoreDiscriminator: boolean): Type {
    return value as Type;
}

