/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    telephone?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    town?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    emergencyName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    emergencyTelephone?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    emergencyRelationship?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    activatedAt?: Date;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'street': json['street'] == null ? undefined : json['street'],
        'town': json['town'] == null ? undefined : json['town'],
        'region': json['region'] == null ? undefined : json['region'],
        'postcode': json['postcode'] == null ? undefined : json['postcode'],
        'emergencyName': json['emergency_name'] == null ? undefined : json['emergency_name'],
        'emergencyTelephone': json['emergency_telephone'] == null ? undefined : json['emergency_telephone'],
        'emergencyRelationship': json['emergency_relationship'] == null ? undefined : json['emergency_relationship'],
        'activatedAt': json['activated_at'] == null ? undefined : (new Date(json['activated_at'])),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'telephone': value['telephone'],
        'street': value['street'],
        'town': value['town'],
        'region': value['region'],
        'postcode': value['postcode'],
        'emergency_name': value['emergencyName'],
        'emergency_telephone': value['emergencyTelephone'],
        'emergency_relationship': value['emergencyRelationship'],
        'activated_at': value['activatedAt'] == null ? undefined : ((value['activatedAt']).toISOString()),
    };
}

