/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VenueCoordinates
 */
export interface VenueCoordinates {
    /**
     * 
     * @type {number}
     * @memberof VenueCoordinates
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof VenueCoordinates
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof VenueCoordinates
     */
    accuracy?: number;
}

/**
 * Check if a given object implements the VenueCoordinates interface.
 */
export function instanceOfVenueCoordinates(value: object): value is VenueCoordinates {
    return true;
}

export function VenueCoordinatesFromJSON(json: any): VenueCoordinates {
    return VenueCoordinatesFromJSONTyped(json, false);
}

export function VenueCoordinatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueCoordinates {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'accuracy': json['accuracy'] == null ? undefined : json['accuracy'],
    };
}

export function VenueCoordinatesToJSON(json: any): VenueCoordinates {
    return VenueCoordinatesToJSONTyped(json, false);
}

export function VenueCoordinatesToJSONTyped(value?: VenueCoordinates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'accuracy': value['accuracy'],
    };
}

