/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Venue
 */
export interface Venue {
    /**
     * 
     * @type {number}
     * @memberof Venue
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    address: string;
    /**
     * 
     * @type {number}
     * @memberof Venue
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof Venue
     */
    longitude: number;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    information?: string;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    parking?: string;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    landmarks?: string;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    changingFacilities?: string;
}

/**
 * Check if a given object implements the Venue interface.
 */
export function instanceOfVenue(value: object): value is Venue {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function VenueFromJSON(json: any): Venue {
    return VenueFromJSONTyped(json, false);
}

export function VenueFromJSONTyped(json: any, ignoreDiscriminator: boolean): Venue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'address': json['address'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'information': json['information'] == null ? undefined : json['information'],
        'parking': json['parking'] == null ? undefined : json['parking'],
        'landmarks': json['landmarks'] == null ? undefined : json['landmarks'],
        'changingFacilities': json['changing_facilities'] == null ? undefined : json['changing_facilities'],
    };
}

export function VenueToJSON(json: any): Venue {
    return VenueToJSONTyped(json, false);
}

export function VenueToJSONTyped(value?: Venue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'address': value['address'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'information': value['information'],
        'parking': value['parking'],
        'landmarks': value['landmarks'],
        'changing_facilities': value['changingFacilities'],
    };
}

