/* tslint:disable */
/* eslint-disable */
/**
 * DoDays API
 * The DoDays API reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engineering@dodays.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Voucher
 */
export interface Voucher {
    /**
     * 
     * @type {number}
     * @memberof Voucher
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Voucher
     */
    value?: number;
    /**
     * 
     * @type {number}
     * @memberof Voucher
     */
    remainingValue?: number;
}

/**
 * Check if a given object implements the Voucher interface.
 */
export function instanceOfVoucher(value: object): value is Voucher {
    return true;
}

export function VoucherFromJSON(json: any): Voucher {
    return VoucherFromJSONTyped(json, false);
}

export function VoucherFromJSONTyped(json: any, ignoreDiscriminator: boolean): Voucher {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : json['value'],
        'remainingValue': json['remaining_value'] == null ? undefined : json['remaining_value'],
    };
}

export function VoucherToJSON(json: any): Voucher {
    return VoucherToJSONTyped(json, false);
}

export function VoucherToJSONTyped(value?: Voucher | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value': value['value'],
        'remaining_value': value['remainingValue'],
    };
}

